-- AUTO-GENERATED by schema.sh
-- Generated at: 2025-12-26T15:40:30Z
-- Source: migrations/*.sql

-- =====================================================================
-- SOURCE: 20251214120953_init_extension.sql
-- =====================================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;



-- =====================================================================
-- SOURCE: 20251214121038_create_users_profiles_table.sql
-- =====================================================================


CREATE TYPE auth_provider AS ENUM ('google', 'credential');
CREATE TABLE IF NOT EXISTS profiles (
    -- Tambahkan DEFAULT gen_random_uuid()
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), 
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,

    -- Gunakan sql.NullString di Go nantinya
    image_url VARCHAR(255),
    country_code VARCHAR(4),
    phone VARCHAR(20),
    description TEXT,

    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP

);

CREATE TRIGGER trigger_profiles_updated_at
BEFORE UPDATE ON profiles
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    password VARCHAR(255),
    provider auth_provider NOT NULL,
    verified_at TIMESTAMPTZ,

    -- Tambahkan NOT NULL agar di Go tipenya uuid.UUID (bukan NullUUID)
    profile_id UUID NOT NULL, 
    FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE,

    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP

);

CREATE TRIGGER trigger_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();




-- =====================================================================
-- SOURCE: 20251218125633_create_business_bknowledge_bproduct_brole_brsssubscription.sql
-- =====================================================================

CREATE TABLE IF NOT EXISTS business_roots ( 
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 1 to 1 with business_root
CREATE TABLE IF NOT EXISTS business_knowledges ( 
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    name VARCHAR(255) NOT NULL,
    primary_logo_url VARCHAR(255),
    category VARCHAR(255) NOT NULL,
    description TEXT,

    unique_selling_point TEXT,
    website_url VARCHAR(255),
    vision_mission TEXT,
    location VARCHAR(255),
    color_tone VARCHAR(6),

    business_root_id UUID NOT NULL UNIQUE,
    FOREIGN KEY (business_root_id) REFERENCES business_roots(id) ON DELETE CASCADE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

-- 1 to many with business_root
CREATE TABLE IF NOT EXISTS business_products ( 
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    name VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    description TEXT,

    currency CHAR(3) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,

    image_urls VARCHAR(255)[] NOT NULL,

    business_root_id UUID NOT NULL,
    FOREIGN KEY (business_root_id) REFERENCES business_roots(id) ON DELETE CASCADE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

-- 1 to 1 with business_root
CREATE TABLE IF NOT EXISTS business_roles ( 
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    target_audience VARCHAR(255) NOT NULL,
    tone VARCHAR(255) NOT NULL,
    audience_persona VARCHAR(255) NOT NULL,
    hashtags VARCHAR(255)[] NOT NULL,
    call_to_action VARCHAR(255) NOT NULL,
    goals TEXT,

    business_root_id UUID NOT NULL UNIQUE,
    FOREIGN KEY (business_root_id) REFERENCES business_roots(id) ON DELETE CASCADE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

-- 1 to many with business_root
CREATE TABLE IF NOT EXISTS business_rss_subscriptions ( 
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    title VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL,

    business_root_id UUID NOT NULL,
    FOREIGN KEY (business_root_id) REFERENCES business_roots(id) ON DELETE CASCADE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

-- Func for trigger root
CREATE OR REPLACE FUNCTION touch_business_root_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE business_roots
    SET updated_at = CURRENT_TIMESTAMP
    WHERE id = NEW.business_root_id;

    RETURN NEW;

  ELSIF TG_OP = 'UPDATE' THEN
    -- Kalau pindah root, touch root lama juga
    IF OLD.business_root_id IS DISTINCT FROM NEW.business_root_id THEN
      UPDATE business_roots
      SET updated_at = CURRENT_TIMESTAMP
      WHERE id = OLD.business_root_id;
    END IF;

    UPDATE business_roots
    SET updated_at = CURRENT_TIMESTAMP
    WHERE id = NEW.business_root_id;

    RETURN NEW;

  ELSIF TG_OP = 'DELETE' THEN
    UPDATE business_roots
    SET updated_at = CURRENT_TIMESTAMP
    WHERE id = OLD.business_root_id;

    RETURN OLD;
  END IF;

  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- Trigger Each Table

CREATE TRIGGER trg_business_roots_set_updated_at
BEFORE UPDATE ON business_roots
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_business_knowledges_set_updated_at
BEFORE UPDATE ON business_knowledges
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_business_products_set_updated_at
BEFORE UPDATE ON business_products
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_business_roles_set_updated_at
BEFORE UPDATE ON business_roles
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_business_rss_subscriptions_set_updated_at
BEFORE UPDATE ON business_rss_subscriptions
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- Trigger For Root
CREATE TRIGGER trg_touch_root_from_knowledges
AFTER INSERT OR UPDATE OR DELETE ON business_knowledges
FOR EACH ROW
EXECUTE FUNCTION touch_business_root_updated_at();

CREATE TRIGGER trg_touch_root_from_products
AFTER INSERT OR UPDATE OR DELETE ON business_products
FOR EACH ROW
EXECUTE FUNCTION touch_business_root_updated_at();

CREATE TRIGGER trg_touch_root_from_roles
AFTER INSERT OR UPDATE OR DELETE ON business_roles
FOR EACH ROW
EXECUTE FUNCTION touch_business_root_updated_at();

CREATE TRIGGER trg_touch_root_from_rss_subscriptions
AFTER INSERT OR UPDATE OR DELETE ON business_rss_subscriptions
FOR EACH ROW
EXECUTE FUNCTION touch_business_root_updated_at();





-- =====================================================================
-- SOURCE: 20251218133145_create_members_table.sql
-- =====================================================================


CREATE TYPE business_member_status AS ENUM ('pending', 'accepted', 'rejected', 'left', 'kicked');
CREATE TYPE business_member_role   AS ENUM ('owner', 'admin', 'member');

CREATE TABLE IF NOT EXISTS business_members (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    status business_member_status NOT NULL DEFAULT 'pending',
    role   business_member_role   NOT NULL DEFAULT 'member',

    answered_at TIMESTAMPTZ,

    business_root_id UUID NOT NULL,
    profile_id       UUID NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT business_members_root_profile_unique UNIQUE (business_root_id, profile_id),

    FOREIGN KEY (business_root_id) REFERENCES business_roots(id) ON DELETE CASCADE,
    FOREIGN KEY (profile_id)       REFERENCES profiles(id)       ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_business_members_business_root_id ON business_members(business_root_id);
CREATE INDEX IF NOT EXISTS idx_business_members_profile_id       ON business_members(profile_id);

CREATE TRIGGER trigger_business_members_updated_at
BEFORE UPDATE ON business_members
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();





-- =====================================================================
-- SOURCE: 20251219180214_alter_business_root_add_deleted_at.sql
-- =====================================================================

ALTER TABLE business_roots
ADD COLUMN deleted_at TIMESTAMPTZ;



-- =====================================================================
-- SOURCE: 20251219183004_alter_business_member_add_deleted_at.sql
-- =====================================================================

ALTER TABLE business_members ADD COLUMN deleted_at TIMESTAMPTZ;



-- =====================================================================
-- SOURCE: 20251221122112_alter_business_products_bigint_price_drop_unused_products.sql
-- =====================================================================

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM business_products
        WHERE price != FLOOR(price)
    ) THEN
        RAISE EXCEPTION 'price contains decimal values';
    END IF;
END $$;

ALTER TABLE business_products
    ALTER COLUMN price TYPE BIGINT
    USING price::BIGINT;




-- =====================================================================
-- SOURCE: 20251221135856_create_uploaded_images_table.sql
-- =====================================================================

CREATE TYPE image_provider AS ENUM ('cloudinary');

CREATE TABLE uploaded_images (
    id BIGSERIAL PRIMARY KEY,
    hashkey VARCHAR(255) NOT NULL UNIQUE,
    public_id VARCHAR(255) NOT NULL,
    size BIGINT NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    provider image_provider NOT NULL,
    format VARCHAR(8) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);




-- =====================================================================
-- SOURCE: 20251225112121_create_app_rss_app_rss_category_table.sql
-- =====================================================================

CREATE TABLE app_rss_categories (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	name VARCHAR(255) NOT NULL,
	deleted_at TIMESTAMPTZ,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER trigger_app_rss_categories_updated_at
BEFORE UPDATE ON app_rss_categories
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE app_rss_feeds (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	title VARCHAR(255) NOT NULL,
	url VARCHAR(255) NOT NULL,
	publisher VARCHAR(255) NOT NULL,
	app_rss_category_id UUID NOT NULL,
	FOREIGN KEY (app_rss_category_id) REFERENCES app_rss_categories(id),
	deleted_at TIMESTAMPTZ,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER trigger_app_rss_feeds_updated_at
BEFORE UPDATE ON app_rss_feeds
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();



-- =====================================================================
-- SOURCE: 20251225123316_alter_business_rss_subscriptions_table.sql
-- =====================================================================

-- Relasi: business_rss_subscriptions (*) -> app_rss_feeds (1)

ALTER TABLE business_rss_subscriptions
ADD COLUMN IF NOT EXISTS app_rss_feed_id UUID NOT NULL;

ALTER TABLE business_rss_subscriptions
ADD CONSTRAINT fk_business_rss_subscriptions_app_rss_feed_id
FOREIGN KEY (app_rss_feed_id)
REFERENCES app_rss_feeds(id)
ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS idx_business_rss_subscriptions_app_rss_feed_id
ON business_rss_subscriptions(app_rss_feed_id);



-- =====================================================================
-- SOURCE: 20251225211811_create_business_timezone_prefs_table.sql
-- =====================================================================

-- 1 to 1 with business_roots(id)
CREATE TABLE IF NOT EXISTS business_timezone_prefs (
	id SERIAL PRIMARY KEY,
	business_root_id UUID NOT NULL UNIQUE,
    FOREIGN KEY (business_root_id) REFERENCES business_roots (id) ON DELETE CASCADE,
	timezone VARCHAR(255) NOT NULL DEFAULT 'Asia/Jakarta',
	created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE TRIGGER trg_business_timezone_prefs_set_updated_at
BEFORE UPDATE ON business_timezone_prefs
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_touch_root_from_timezone_prefs
AFTER INSERT OR UPDATE OR DELETE ON business_timezone_prefs
FOR EACH ROW
EXECUTE FUNCTION touch_business_root_updated_at();



-- =====================================================================
-- SOURCE: 20251226135819_create_creator_images_and_app_creator_image_type_categories_and_app_creator_image_product_categories_table.sql
-- =====================================================================


-- ex: announcement, entertainment, marketing, etc
CREATE TABLE IF NOT EXISTS app_creator_image_type_categories (
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER trigger_app_creator_image_type_categories_updated_at
BEFORE UPDATE ON app_creator_image_type_categories
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- ex: fashion & lifestyle, makanan & minuman, etc
CREATE TABLE IF NOT EXISTS app_creator_image_product_categories (
	id BIGSERIAL PRIMARY KEY,
    indonesian_name VARCHAR(255) NOT NULL,
    english_name VARCHAR(255) NOT NULL,
	created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER trigger_app_creator_image_product_categories_updated_at
BEFORE UPDATE ON app_creator_image_product_categories
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- base table (tanpa FK category)
CREATE TABLE IF NOT EXISTS creator_images (
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	image_url TEXT NOT NULL,
    is_published BOOLEAN NOT NULL DEFAULT FALSE,
    is_banned BOOLEAN NOT NULL DEFAULT FALSE,
    banned_reason TEXT,
    price BIGINT,

	-- creator profile (if null -> template from app/postmatic)
	profile_id UUID,
    CONSTRAINT fk_creator_images_profile
		FOREIGN KEY (profile_id) REFERENCES profiles(id),

	created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMPTZ
);

CREATE TRIGGER trigger_creator_images_updated_at
BEFORE UPDATE ON creator_images
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- pivot: creator_images <-> product categories
CREATE TABLE IF NOT EXISTS creator_image_product_categories (
	creator_image_id BIGINT NOT NULL,
	product_category_id BIGINT NOT NULL,
	created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT pk_creator_image_product_categories
		PRIMARY KEY (creator_image_id, product_category_id),

	CONSTRAINT fk_cipc_creator_image
		FOREIGN KEY (creator_image_id) REFERENCES creator_images(id) ON DELETE CASCADE,

	-- biasanya NO ACTION/RESTRICT biar category tidak bisa dihapus kalau masih dipakai
	CONSTRAINT fk_cipc_product_category
		FOREIGN KEY (product_category_id) REFERENCES app_creator_image_product_categories(id)
);

CREATE INDEX IF NOT EXISTS idx_cipc_creator_image_id
	ON creator_image_product_categories(creator_image_id);

CREATE INDEX IF NOT EXISTS idx_cipc_product_category_id
	ON creator_image_product_categories(product_category_id);


-- pivot: creator_images <-> type categories
CREATE TABLE IF NOT EXISTS creator_image_type_categories (
	creator_image_id BIGINT NOT NULL,
	type_category_id BIGINT NOT NULL,
	created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT pk_creator_image_type_categories
		PRIMARY KEY (creator_image_id, type_category_id),

	CONSTRAINT fk_citc_creator_image
		FOREIGN KEY (creator_image_id) REFERENCES creator_images(id) ON DELETE CASCADE,

	CONSTRAINT fk_citc_type_category
		FOREIGN KEY (type_category_id) REFERENCES app_creator_image_type_categories(id)
);

CREATE INDEX IF NOT EXISTS idx_citc_creator_image_id
	ON creator_image_type_categories(creator_image_id);

CREATE INDEX IF NOT EXISTS idx_citc_type_category_id
	ON creator_image_type_categories(type_category_id);





