#!/usr/bin/env bash
set -euo pipefail

# Usage:
#   ./schema.sh                 # migrations -> ./migration_record.sql
#   ./schema.sh migrations out.sql

MIGRATIONS_DIR="${1:-migrations}"
OUT_FILE="${2:-migration_record.sql}"

if [[ ! -d "$MIGRATIONS_DIR" ]]; then
  echo "ERROR: directory not found: $MIGRATIONS_DIR" >&2
  exit 1
fi

# consistent ordering
export LC_ALL=C

tmp="$(mktemp -t migration_record.XXXXXX)"
trap 'rm -f "$tmp"' EXIT

{
  echo "-- AUTO-GENERATED by schema.sh"
  echo "-- Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo "-- Source: ${MIGRATIONS_DIR}/*.sql"
  echo
} > "$tmp"

# Avoid literal glob when no files exist
shopt -s nullglob

count=0
found_any=0

for file in "$MIGRATIONS_DIR"/*.sql; do
  found_any=1
  count=$((count + 1))

  {
    echo "-- ====================================================================="
    echo "-- SOURCE: $(basename "$file")"
    echo "-- ====================================================================="
    echo
  } >> "$tmp"

  # Extract only the "Up" section and drop goose directive lines
  awk '
    BEGIN { in_up=0 }
    # Start capturing after "-- +goose Up"
    /^--[[:space:]]*\+goose[[:space:]]+Up[[:space:]]*$/ { in_up=1; next }
    # Stop capturing when "-- +goose Down" appears
    /^--[[:space:]]*\+goose[[:space:]]+Down[[:space:]]*$/ { in_up=0; next }
    # Drop other goose directives inside Up (StatementBegin/End)
    /^--[[:space:]]*\+goose[[:space:]]+(StatementBegin|StatementEnd)[[:space:]]*$/ { next }
    # Print only lines inside Up
    { if (in_up) print }
  ' "$file" >> "$tmp"

  # Ensure spacing between migrations
  echo -e "\n" >> "$tmp"
done

if [[ "$found_any" -eq 0 ]]; then
  echo "ERROR: no .sql migrations found in: $MIGRATIONS_DIR" >&2
  exit 1
fi

mv "$tmp" "$OUT_FILE"
trap - EXIT

echo "OK: wrote $OUT_FILE from $count migration file(s)."
