// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_profile_referral_change.sql

package entity

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const insertAppProfileReferralChange = `-- name: InsertAppProfileReferralChange :one
INSERT INTO app_profile_referral_changes (
  profile_id,
  total_discount,
  discount_type,
  expired_days,
  max_discount,
  max_usage,
  reward_per_referral
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
RETURNING id, profile_id, total_discount, discount_type, expired_days, max_discount, max_usage, reward_per_referral, created_at, updated_at
`

type InsertAppProfileReferralChangeParams struct {
	ProfileID         uuid.UUID     `json:"profile_id"`
	TotalDiscount     int64         `json:"total_discount"`
	DiscountType      DiscountType  `json:"discount_type"`
	ExpiredDays       sql.NullInt32 `json:"expired_days"`
	MaxDiscount       int64         `json:"max_discount"`
	MaxUsage          sql.NullInt32 `json:"max_usage"`
	RewardPerReferral int64         `json:"reward_per_referral"`
}

func (q *Queries) InsertAppProfileReferralChange(ctx context.Context, arg InsertAppProfileReferralChangeParams) (AppProfileReferralChange, error) {
	row := q.db.QueryRowContext(ctx, insertAppProfileReferralChange,
		arg.ProfileID,
		arg.TotalDiscount,
		arg.DiscountType,
		arg.ExpiredDays,
		arg.MaxDiscount,
		arg.MaxUsage,
		arg.RewardPerReferral,
	)
	var i AppProfileReferralChange
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.TotalDiscount,
		&i.DiscountType,
		&i.ExpiredDays,
		&i.MaxDiscount,
		&i.MaxUsage,
		&i.RewardPerReferral,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
