// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_profile_referral_rules.sql

package entity

import (
	"context"
	"database/sql"
)

const getAppProfileReferralRules = `-- name: GetAppProfileReferralRules :one
SELECT
  id,
  total_discount,
  discount_type,
  expired_days,
  max_discount,
  max_usage,
  reward_per_referral,
  created_at,
  updated_at
FROM app_profile_referral_rules
WHERE id = 1
`

func (q *Queries) GetAppProfileReferralRules(ctx context.Context) (AppProfileReferralRule, error) {
	row := q.db.QueryRowContext(ctx, getAppProfileReferralRules)
	var i AppProfileReferralRule
	err := row.Scan(
		&i.ID,
		&i.TotalDiscount,
		&i.DiscountType,
		&i.ExpiredDays,
		&i.MaxDiscount,
		&i.MaxUsage,
		&i.RewardPerReferral,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAppProfileReferralRules = `-- name: UpsertAppProfileReferralRules :one
INSERT INTO app_profile_referral_rules (
  id,
  total_discount,
  discount_type,
  expired_days,
  max_discount,
  max_usage,
  reward_per_referral
)
VALUES (
  1,
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
ON CONFLICT (id) DO UPDATE
SET
  total_discount       = EXCLUDED.total_discount,
  discount_type        = EXCLUDED.discount_type,
  expired_days         = EXCLUDED.expired_days,
  max_discount         = EXCLUDED.max_discount,
  max_usage            = EXCLUDED.max_usage,
  reward_per_referral  = EXCLUDED.reward_per_referral

RETURNING
  id,
  total_discount,
  discount_type,
  expired_days,
  max_discount,
  max_usage,
  reward_per_referral,
  created_at,
  updated_at
`

type UpsertAppProfileReferralRulesParams struct {
	TotalDiscount     int64         `json:"total_discount"`
	DiscountType      DiscountType  `json:"discount_type"`
	ExpiredDays       sql.NullInt32 `json:"expired_days"`
	MaxDiscount       int64         `json:"max_discount"`
	MaxUsage          sql.NullInt32 `json:"max_usage"`
	RewardPerReferral int64         `json:"reward_per_referral"`
}

func (q *Queries) UpsertAppProfileReferralRules(ctx context.Context, arg UpsertAppProfileReferralRulesParams) (AppProfileReferralRule, error) {
	row := q.db.QueryRowContext(ctx, upsertAppProfileReferralRules,
		arg.TotalDiscount,
		arg.DiscountType,
		arg.ExpiredDays,
		arg.MaxDiscount,
		arg.MaxUsage,
		arg.RewardPerReferral,
	)
	var i AppProfileReferralRule
	err := row.Scan(
		&i.ID,
		&i.TotalDiscount,
		&i.DiscountType,
		&i.ExpiredDays,
		&i.MaxDiscount,
		&i.MaxUsage,
		&i.RewardPerReferral,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
