// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_generative_text_model.sql

package entity

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countAllGenerativeTextModels = `-- name: CountAllGenerativeTextModels :one
SELECT COUNT(*)::bigint AS total
FROM app_generative_text_models g
WHERE
  g.deleted_at IS NULL
  AND (
    COALESCE($1, '') = ''
    OR g.model ILIKE ('%' || $1 || '%')
    OR g.label ILIKE ('%' || $1 || '%')
  )
  AND (
    $2::boolean = TRUE
    OR g.is_active = TRUE
  )
`

type CountAllGenerativeTextModelsParams struct {
	Search  interface{} `json:"search"`
	IsAdmin bool        `json:"is_admin"`
}

func (q *Queries) CountAllGenerativeTextModels(ctx context.Context, arg CountAllGenerativeTextModelsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllGenerativeTextModels, arg.Search, arg.IsAdmin)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createGenerativeTextModel = `-- name: CreateGenerativeTextModel :one
INSERT INTO app_generative_text_models (
  model,
  label,
  image,
  provider,
  is_active
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, model, label, image, provider, is_active, created_at, updated_at, deleted_at
`

type CreateGenerativeTextModelParams struct {
	Model    string                             `json:"model"`
	Label    string                             `json:"label"`
	Image    sql.NullString                     `json:"image"`
	Provider AppGenerativeTextModelProviderType `json:"provider"`
	IsActive bool                               `json:"is_active"`
}

func (q *Queries) CreateGenerativeTextModel(ctx context.Context, arg CreateGenerativeTextModelParams) (AppGenerativeTextModel, error) {
	row := q.db.QueryRowContext(ctx, createGenerativeTextModel,
		arg.Model,
		arg.Label,
		arg.Image,
		arg.Provider,
		arg.IsActive,
	)
	var i AppGenerativeTextModel
	err := row.Scan(
		&i.ID,
		&i.Model,
		&i.Label,
		&i.Image,
		&i.Provider,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createGenerativeTextModelChange = `-- name: CreateGenerativeTextModelChange :one
INSERT INTO app_generative_text_model_changes (
  action,
  profile_id,
  generative_text_model_id,
  before_model,
  before_label,
  before_image,
  before_provider,
  before_is_active,
  after_model,
  after_label,
  after_image,
  after_provider,
  after_is_active
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
) RETURNING id, action, profile_id, generative_text_model_id, before_model, before_label, before_image, before_provider, before_is_active, after_model, after_label, after_image, after_provider, after_is_active, created_at, updated_at, deleted_at
`

type CreateGenerativeTextModelChangeParams struct {
	Action                ActionChangeType                   `json:"action"`
	ProfileID             uuid.UUID                          `json:"profile_id"`
	GenerativeTextModelID int64                              `json:"generative_text_model_id"`
	BeforeModel           string                             `json:"before_model"`
	BeforeLabel           string                             `json:"before_label"`
	BeforeImage           sql.NullString                     `json:"before_image"`
	BeforeProvider        AppGenerativeTextModelProviderType `json:"before_provider"`
	BeforeIsActive        bool                               `json:"before_is_active"`
	AfterModel            string                             `json:"after_model"`
	AfterLabel            string                             `json:"after_label"`
	AfterImage            sql.NullString                     `json:"after_image"`
	AfterProvider         AppGenerativeTextModelProviderType `json:"after_provider"`
	AfterIsActive         bool                               `json:"after_is_active"`
}

func (q *Queries) CreateGenerativeTextModelChange(ctx context.Context, arg CreateGenerativeTextModelChangeParams) (AppGenerativeTextModelChange, error) {
	row := q.db.QueryRowContext(ctx, createGenerativeTextModelChange,
		arg.Action,
		arg.ProfileID,
		arg.GenerativeTextModelID,
		arg.BeforeModel,
		arg.BeforeLabel,
		arg.BeforeImage,
		arg.BeforeProvider,
		arg.BeforeIsActive,
		arg.AfterModel,
		arg.AfterLabel,
		arg.AfterImage,
		arg.AfterProvider,
		arg.AfterIsActive,
	)
	var i AppGenerativeTextModelChange
	err := row.Scan(
		&i.ID,
		&i.Action,
		&i.ProfileID,
		&i.GenerativeTextModelID,
		&i.BeforeModel,
		&i.BeforeLabel,
		&i.BeforeImage,
		&i.BeforeProvider,
		&i.BeforeIsActive,
		&i.AfterModel,
		&i.AfterLabel,
		&i.AfterImage,
		&i.AfterProvider,
		&i.AfterIsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAllGenerativeTextModels = `-- name: GetAllGenerativeTextModels :many
SELECT
  g.id, g.model, g.label, g.image, g.provider, g.is_active, g.created_at, g.updated_at, g.deleted_at
FROM app_generative_text_models g
WHERE
  g.deleted_at IS NULL
  AND (
    COALESCE($1, '') = ''
    OR g.model ILIKE ('%' || $1 || '%')
    OR g.label ILIKE ('%' || $1 || '%')
  )
  AND (
    $2::boolean = TRUE
    OR g.is_active = TRUE
  )
ORDER BY
  -- label
  CASE WHEN $3 = 'label' AND $4 = 'asc'  THEN g.label END ASC,
  CASE WHEN $3 = 'label' AND $4 = 'desc' THEN g.label END DESC,

  -- model
  CASE WHEN $3 = 'model' AND $4 = 'asc'  THEN g.model END ASC,
  CASE WHEN $3 = 'model' AND $4 = 'desc' THEN g.model END DESC,

  -- created_at
  CASE WHEN $3 = 'created_at' AND $4 = 'asc'  THEN g.created_at END ASC,
  CASE WHEN $3 = 'created_at' AND $4 = 'desc' THEN g.created_at END DESC,

  -- updated_at
  CASE WHEN $3 = 'updated_at' AND $4 = 'asc'  THEN g.updated_at END ASC,
  CASE WHEN $3 = 'updated_at' AND $4 = 'desc' THEN g.updated_at END DESC,

  -- id
  CASE WHEN $3 = 'id' AND $4 = 'asc'  THEN g.id END ASC,
  CASE WHEN $3 = 'id' AND $4 = 'desc' THEN g.id END DESC,

  -- fallback stable order
  g.id DESC
LIMIT $6
OFFSET $5
`

type GetAllGenerativeTextModelsParams struct {
	Search     interface{} `json:"search"`
	IsAdmin    bool        `json:"is_admin"`
	SortBy     interface{} `json:"sort_by"`
	SortDir    interface{} `json:"sort_dir"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

func (q *Queries) GetAllGenerativeTextModels(ctx context.Context, arg GetAllGenerativeTextModelsParams) ([]AppGenerativeTextModel, error) {
	rows, err := q.db.QueryContext(ctx, getAllGenerativeTextModels,
		arg.Search,
		arg.IsAdmin,
		arg.SortBy,
		arg.SortDir,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppGenerativeTextModel
	for rows.Next() {
		var i AppGenerativeTextModel
		if err := rows.Scan(
			&i.ID,
			&i.Model,
			&i.Label,
			&i.Image,
			&i.Provider,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGenerativeTextModelById = `-- name: GetGenerativeTextModelById :one
SELECT id, model, label, image, provider, is_active, created_at, updated_at, deleted_at FROM app_generative_text_models
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetGenerativeTextModelById(ctx context.Context, id int64) (AppGenerativeTextModel, error) {
	row := q.db.QueryRowContext(ctx, getGenerativeTextModelById, id)
	var i AppGenerativeTextModel
	err := row.Scan(
		&i.ID,
		&i.Model,
		&i.Label,
		&i.Image,
		&i.Provider,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGenerativeTextModelByIdAdmin = `-- name: GetGenerativeTextModelByIdAdmin :one
SELECT id, model, label, image, provider, is_active, created_at, updated_at, deleted_at FROM app_generative_text_models
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetGenerativeTextModelByIdAdmin(ctx context.Context, id int64) (AppGenerativeTextModel, error) {
	row := q.db.QueryRowContext(ctx, getGenerativeTextModelByIdAdmin, id)
	var i AppGenerativeTextModel
	err := row.Scan(
		&i.ID,
		&i.Model,
		&i.Label,
		&i.Image,
		&i.Provider,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGenerativeTextModelByIdUser = `-- name: GetGenerativeTextModelByIdUser :one
SELECT id, model, label, image, provider, is_active, created_at, updated_at, deleted_at FROM app_generative_text_models
WHERE id = $1 AND deleted_at IS NULL AND is_active = TRUE
`

func (q *Queries) GetGenerativeTextModelByIdUser(ctx context.Context, id int64) (AppGenerativeTextModel, error) {
	row := q.db.QueryRowContext(ctx, getGenerativeTextModelByIdUser, id)
	var i AppGenerativeTextModel
	err := row.Scan(
		&i.ID,
		&i.Model,
		&i.Label,
		&i.Image,
		&i.Provider,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGenerativeTextModelByModel = `-- name: GetGenerativeTextModelByModel :one
SELECT id, model, label, image, provider, is_active, created_at, updated_at, deleted_at FROM app_generative_text_models
WHERE model = $1 AND deleted_at IS NULL
`

func (q *Queries) GetGenerativeTextModelByModel(ctx context.Context, model string) (AppGenerativeTextModel, error) {
	row := q.db.QueryRowContext(ctx, getGenerativeTextModelByModel, model)
	var i AppGenerativeTextModel
	err := row.Scan(
		&i.ID,
		&i.Model,
		&i.Label,
		&i.Image,
		&i.Provider,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGenerativeTextModelByModelAdmin = `-- name: GetGenerativeTextModelByModelAdmin :one
SELECT id, model, label, image, provider, is_active, created_at, updated_at, deleted_at FROM app_generative_text_models
WHERE model = $1 AND deleted_at IS NULL
`

func (q *Queries) GetGenerativeTextModelByModelAdmin(ctx context.Context, model string) (AppGenerativeTextModel, error) {
	row := q.db.QueryRowContext(ctx, getGenerativeTextModelByModelAdmin, model)
	var i AppGenerativeTextModel
	err := row.Scan(
		&i.ID,
		&i.Model,
		&i.Label,
		&i.Image,
		&i.Provider,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGenerativeTextModelByModelUser = `-- name: GetGenerativeTextModelByModelUser :one
SELECT id, model, label, image, provider, is_active, created_at, updated_at, deleted_at FROM app_generative_text_models
WHERE model = $1 AND deleted_at IS NULL AND is_active = TRUE
`

func (q *Queries) GetGenerativeTextModelByModelUser(ctx context.Context, model string) (AppGenerativeTextModel, error) {
	row := q.db.QueryRowContext(ctx, getGenerativeTextModelByModelUser, model)
	var i AppGenerativeTextModel
	err := row.Scan(
		&i.ID,
		&i.Model,
		&i.Label,
		&i.Image,
		&i.Provider,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteGenerativeTextModel = `-- name: SoftDeleteGenerativeTextModel :one
UPDATE app_generative_text_models
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, model, label, image, provider, is_active, created_at, updated_at, deleted_at
`

func (q *Queries) SoftDeleteGenerativeTextModel(ctx context.Context, id int64) (AppGenerativeTextModel, error) {
	row := q.db.QueryRowContext(ctx, softDeleteGenerativeTextModel, id)
	var i AppGenerativeTextModel
	err := row.Scan(
		&i.ID,
		&i.Model,
		&i.Label,
		&i.Image,
		&i.Provider,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateGenerativeTextModel = `-- name: UpdateGenerativeTextModel :one
UPDATE app_generative_text_models
SET
  model = $2,
  label = $3,
  image = $4,
  provider = $5,
  is_active = $6
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, model, label, image, provider, is_active, created_at, updated_at, deleted_at
`

type UpdateGenerativeTextModelParams struct {
	ID       int64                              `json:"id"`
	Model    string                             `json:"model"`
	Label    string                             `json:"label"`
	Image    sql.NullString                     `json:"image"`
	Provider AppGenerativeTextModelProviderType `json:"provider"`
	IsActive bool                               `json:"is_active"`
}

func (q *Queries) UpdateGenerativeTextModel(ctx context.Context, arg UpdateGenerativeTextModelParams) (AppGenerativeTextModel, error) {
	row := q.db.QueryRowContext(ctx, updateGenerativeTextModel,
		arg.ID,
		arg.Model,
		arg.Label,
		arg.Image,
		arg.Provider,
		arg.IsActive,
	)
	var i AppGenerativeTextModel
	err := row.Scan(
		&i.ID,
		&i.Model,
		&i.Label,
		&i.Image,
		&i.Provider,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
