// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_creator_image_product_category.sql

package entity

import (
	"context"

	"github.com/lib/pq"
)

const countAllAppCreatorImageProductCategories = `-- name: CountAllAppCreatorImageProductCategories :one
SELECT COUNT(*)::bigint AS total
FROM app_creator_image_product_categories c
WHERE
  $1 = ''
  OR c.indonesian_name ILIKE ('%' || $1 || '%')
  OR c.english_name ILIKE ('%' || $1 || '%')
`

func (q *Queries) CountAllAppCreatorImageProductCategories(ctx context.Context, search interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllAppCreatorImageProductCategories, search)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getAllAppCreatorImageProductCategories = `-- name: GetAllAppCreatorImageProductCategories :many
WITH p0 AS (
  SELECT
    lower(COALESCE(NULLIF($3,  ''), '')) AS sb_in,
    lower(COALESCE(NULLIF($4, ''), '')) AS sd_in,
    lower(COALESCE(NULLIF($5,   ''), '')) AS loc_in
),
p AS (
  SELECT
    CASE
      WHEN sb_in IN ('name', 'created_at', 'updated_at') THEN sb_in
      ELSE 'created_at'
    END AS sort_by,
    CASE
      WHEN sd_in IN ('asc', 'desc') THEN sd_in
      ELSE 'desc'
    END AS sort_dir,
    CASE
      WHEN loc_in IN ('id', 'en') THEN loc_in
      ELSE 'id'
    END AS locale
  FROM p0
),
q AS (
  SELECT
    c.id,
    c.indonesian_name,
    c.english_name,
    c.created_at,
    c.updated_at,
    COUNT(DISTINCT cipc.creator_image_id)::bigint AS total_data
  FROM app_creator_image_product_categories c
  LEFT JOIN creator_image_product_categories cipc
    ON cipc.product_category_id = c.id
  LEFT JOIN creator_images ci
    ON ci.id = cipc.creator_image_id
   AND ci.deleted_at IS NULL
  WHERE
    $6 = ''
    OR c.indonesian_name ILIKE ('%' || $6 || '%')
    OR c.english_name ILIKE ('%' || $6 || '%')
  GROUP BY c.id, c.indonesian_name, c.english_name, c.created_at, c.updated_at
)
SELECT
  q.id,
  q.indonesian_name,
  q.english_name,
  q.total_data
FROM q
CROSS JOIN p
ORDER BY
  -- name (depends on locale)
  CASE
    WHEN p.sort_by = 'name' AND p.sort_dir = 'asc'
    THEN (CASE WHEN p.locale = 'en' THEN q.english_name ELSE q.indonesian_name END)
  END ASC,
  CASE
    WHEN p.sort_by = 'name' AND p.sort_dir = 'desc'
    THEN (CASE WHEN p.locale = 'en' THEN q.english_name ELSE q.indonesian_name END)
  END DESC,

  -- created_at (default)
  CASE WHEN p.sort_by = 'created_at' AND p.sort_dir = 'asc'  THEN q.created_at END ASC,
  CASE WHEN p.sort_by = 'created_at' AND p.sort_dir = 'desc' THEN q.created_at END DESC,

  -- updated_at
  CASE WHEN p.sort_by = 'updated_at' AND p.sort_dir = 'asc'  THEN q.updated_at END ASC,
  CASE WHEN p.sort_by = 'updated_at' AND p.sort_dir = 'desc' THEN q.updated_at END DESC,

  -- fallback stable order
  q.created_at DESC,
  q.id DESC
LIMIT $2
OFFSET $1
`

type GetAllAppCreatorImageProductCategoriesParams struct {
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
	SortBy     interface{} `json:"sort_by"`
	SortDir    interface{} `json:"sort_dir"`
	Locale     interface{} `json:"locale"`
	Search     interface{} `json:"search"`
}

type GetAllAppCreatorImageProductCategoriesRow struct {
	ID             int64  `json:"id"`
	IndonesianName string `json:"indonesian_name"`
	EnglishName    string `json:"english_name"`
	TotalData      int64  `json:"total_data"`
}

func (q *Queries) GetAllAppCreatorImageProductCategories(ctx context.Context, arg GetAllAppCreatorImageProductCategoriesParams) ([]GetAllAppCreatorImageProductCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllAppCreatorImageProductCategories,
		arg.PageOffset,
		arg.PageLimit,
		arg.SortBy,
		arg.SortDir,
		arg.Locale,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllAppCreatorImageProductCategoriesRow
	for rows.Next() {
		var i GetAllAppCreatorImageProductCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.IndonesianName,
			&i.EnglishName,
			&i.TotalData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppCreatorImageProductCategoriesByIds = `-- name: GetAppCreatorImageProductCategoriesByIds :many
SELECT
  t.id
FROM app_creator_image_product_categories t
WHERE t.id = ANY($1::bigint[])
`

func (q *Queries) GetAppCreatorImageProductCategoriesByIds(ctx context.Context, ids []int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getAppCreatorImageProductCategoriesByIds, pq.Array(ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
