// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_generative_image_model.sql

package entity

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const countAllGenerativeImageModels = `-- name: CountAllGenerativeImageModels :one
SELECT COUNT(*)::bigint AS total
FROM app_generative_image_models g
WHERE
  g.deleted_at IS NULL
  AND (
    COALESCE($1, '') = ''
    OR g.model ILIKE ('%' || $1 || '%')
    OR g.label ILIKE ('%' || $1 || '%')
  )
  AND (
    $2::boolean = TRUE
    OR g.is_active = TRUE
  )
`

type CountAllGenerativeImageModelsParams struct {
	Search  interface{} `json:"search"`
	IsAdmin bool        `json:"is_admin"`
}

func (q *Queries) CountAllGenerativeImageModels(ctx context.Context, arg CountAllGenerativeImageModelsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllGenerativeImageModels, arg.Search, arg.IsAdmin)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createGenerativeImageModel = `-- name: CreateGenerativeImageModel :one
INSERT INTO app_generative_image_models (
  model,
  label,
  image,
  provider,
  is_active,
  valid_ratios,
  image_sizes
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
) RETURNING id, model, label, image, provider, is_active, valid_ratios, image_sizes, created_at, updated_at, deleted_at
`

type CreateGenerativeImageModelParams struct {
	Model       string                              `json:"model"`
	Label       string                              `json:"label"`
	Image       sql.NullString                      `json:"image"`
	Provider    AppGenerativeImageModelProviderType `json:"provider"`
	IsActive    bool                                `json:"is_active"`
	ValidRatios []string                            `json:"valid_ratios"`
	ImageSizes  []string                            `json:"image_sizes"`
}

func (q *Queries) CreateGenerativeImageModel(ctx context.Context, arg CreateGenerativeImageModelParams) (AppGenerativeImageModel, error) {
	row := q.db.QueryRowContext(ctx, createGenerativeImageModel,
		arg.Model,
		arg.Label,
		arg.Image,
		arg.Provider,
		arg.IsActive,
		pq.Array(arg.ValidRatios),
		pq.Array(arg.ImageSizes),
	)
	var i AppGenerativeImageModel
	err := row.Scan(
		&i.ID,
		&i.Model,
		&i.Label,
		&i.Image,
		&i.Provider,
		&i.IsActive,
		pq.Array(&i.ValidRatios),
		pq.Array(&i.ImageSizes),
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createGenerativeImageModelChange = `-- name: CreateGenerativeImageModelChange :one
INSERT INTO app_generative_image_model_changes (
  action,
  profile_id,
  generative_image_model_id,
  before_model,
  before_label,
  before_image,
  before_provider,
  before_is_active,
  before_valid_ratios,
  before_image_sizes,
  after_model,
  after_label,
  after_image,
  after_provider,
  after_is_active,
  after_valid_ratios,
  after_image_sizes
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
) RETURNING id, action, profile_id, generative_image_model_id, before_model, before_label, before_image, before_provider, before_is_active, before_valid_ratios, before_image_sizes, after_model, after_label, after_image, after_provider, after_is_active, after_valid_ratios, after_image_sizes, created_at, updated_at, deleted_at
`

type CreateGenerativeImageModelChangeParams struct {
	Action                 ActionChangeType                    `json:"action"`
	ProfileID              uuid.UUID                           `json:"profile_id"`
	GenerativeImageModelID int64                               `json:"generative_image_model_id"`
	BeforeModel            string                              `json:"before_model"`
	BeforeLabel            string                              `json:"before_label"`
	BeforeImage            sql.NullString                      `json:"before_image"`
	BeforeProvider         AppGenerativeImageModelProviderType `json:"before_provider"`
	BeforeIsActive         bool                                `json:"before_is_active"`
	BeforeValidRatios      []string                            `json:"before_valid_ratios"`
	BeforeImageSizes       []string                            `json:"before_image_sizes"`
	AfterModel             string                              `json:"after_model"`
	AfterLabel             string                              `json:"after_label"`
	AfterImage             sql.NullString                      `json:"after_image"`
	AfterProvider          AppGenerativeImageModelProviderType `json:"after_provider"`
	AfterIsActive          bool                                `json:"after_is_active"`
	AfterValidRatios       []string                            `json:"after_valid_ratios"`
	AfterImageSizes        []string                            `json:"after_image_sizes"`
}

func (q *Queries) CreateGenerativeImageModelChange(ctx context.Context, arg CreateGenerativeImageModelChangeParams) (AppGenerativeImageModelChange, error) {
	row := q.db.QueryRowContext(ctx, createGenerativeImageModelChange,
		arg.Action,
		arg.ProfileID,
		arg.GenerativeImageModelID,
		arg.BeforeModel,
		arg.BeforeLabel,
		arg.BeforeImage,
		arg.BeforeProvider,
		arg.BeforeIsActive,
		pq.Array(arg.BeforeValidRatios),
		pq.Array(arg.BeforeImageSizes),
		arg.AfterModel,
		arg.AfterLabel,
		arg.AfterImage,
		arg.AfterProvider,
		arg.AfterIsActive,
		pq.Array(arg.AfterValidRatios),
		pq.Array(arg.AfterImageSizes),
	)
	var i AppGenerativeImageModelChange
	err := row.Scan(
		&i.ID,
		&i.Action,
		&i.ProfileID,
		&i.GenerativeImageModelID,
		&i.BeforeModel,
		&i.BeforeLabel,
		&i.BeforeImage,
		&i.BeforeProvider,
		&i.BeforeIsActive,
		pq.Array(&i.BeforeValidRatios),
		pq.Array(&i.BeforeImageSizes),
		&i.AfterModel,
		&i.AfterLabel,
		&i.AfterImage,
		&i.AfterProvider,
		&i.AfterIsActive,
		pq.Array(&i.AfterValidRatios),
		pq.Array(&i.AfterImageSizes),
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAllGenerativeImageModels = `-- name: GetAllGenerativeImageModels :many
SELECT
  g.id, g.model, g.label, g.image, g.provider, g.is_active, g.valid_ratios, g.image_sizes, g.created_at, g.updated_at, g.deleted_at
FROM app_generative_image_models g
WHERE
  g.deleted_at IS NULL
  AND (
    COALESCE($1, '') = ''
    OR g.model ILIKE ('%' || $1 || '%')
    OR g.label ILIKE ('%' || $1 || '%')
  )
  AND (
    $2::boolean = TRUE
    OR g.is_active = TRUE
  )
ORDER BY
  -- label
  CASE WHEN $3 = 'label' AND $4 = 'asc'  THEN g.label END ASC,
  CASE WHEN $3 = 'label' AND $4 = 'desc' THEN g.label END DESC,

  -- model
  CASE WHEN $3 = 'model' AND $4 = 'asc'  THEN g.model END ASC,
  CASE WHEN $3 = 'model' AND $4 = 'desc' THEN g.model END DESC,

  -- created_at
  CASE WHEN $3 = 'created_at' AND $4 = 'asc'  THEN g.created_at END ASC,
  CASE WHEN $3 = 'created_at' AND $4 = 'desc' THEN g.created_at END DESC,

  -- updated_at
  CASE WHEN $3 = 'updated_at' AND $4 = 'asc'  THEN g.updated_at END ASC,
  CASE WHEN $3 = 'updated_at' AND $4 = 'desc' THEN g.updated_at END DESC,

  -- id
  CASE WHEN $3 = 'id' AND $4 = 'asc'  THEN g.id END ASC,
  CASE WHEN $3 = 'id' AND $4 = 'desc' THEN g.id END DESC,

  -- fallback stable order
  g.id DESC
LIMIT $6
OFFSET $5
`

type GetAllGenerativeImageModelsParams struct {
	Search     interface{} `json:"search"`
	IsAdmin    bool        `json:"is_admin"`
	SortBy     interface{} `json:"sort_by"`
	SortDir    interface{} `json:"sort_dir"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

func (q *Queries) GetAllGenerativeImageModels(ctx context.Context, arg GetAllGenerativeImageModelsParams) ([]AppGenerativeImageModel, error) {
	rows, err := q.db.QueryContext(ctx, getAllGenerativeImageModels,
		arg.Search,
		arg.IsAdmin,
		arg.SortBy,
		arg.SortDir,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppGenerativeImageModel
	for rows.Next() {
		var i AppGenerativeImageModel
		if err := rows.Scan(
			&i.ID,
			&i.Model,
			&i.Label,
			&i.Image,
			&i.Provider,
			&i.IsActive,
			pq.Array(&i.ValidRatios),
			pq.Array(&i.ImageSizes),
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGenerativeImageModelById = `-- name: GetGenerativeImageModelById :one
SELECT id, model, label, image, provider, is_active, valid_ratios, image_sizes, created_at, updated_at, deleted_at FROM app_generative_image_models
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetGenerativeImageModelById(ctx context.Context, id int64) (AppGenerativeImageModel, error) {
	row := q.db.QueryRowContext(ctx, getGenerativeImageModelById, id)
	var i AppGenerativeImageModel
	err := row.Scan(
		&i.ID,
		&i.Model,
		&i.Label,
		&i.Image,
		&i.Provider,
		&i.IsActive,
		pq.Array(&i.ValidRatios),
		pq.Array(&i.ImageSizes),
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGenerativeImageModelByIdAdmin = `-- name: GetGenerativeImageModelByIdAdmin :one
SELECT id, model, label, image, provider, is_active, valid_ratios, image_sizes, created_at, updated_at, deleted_at FROM app_generative_image_models
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetGenerativeImageModelByIdAdmin(ctx context.Context, id int64) (AppGenerativeImageModel, error) {
	row := q.db.QueryRowContext(ctx, getGenerativeImageModelByIdAdmin, id)
	var i AppGenerativeImageModel
	err := row.Scan(
		&i.ID,
		&i.Model,
		&i.Label,
		&i.Image,
		&i.Provider,
		&i.IsActive,
		pq.Array(&i.ValidRatios),
		pq.Array(&i.ImageSizes),
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGenerativeImageModelByIdUser = `-- name: GetGenerativeImageModelByIdUser :one
SELECT id, model, label, image, provider, is_active, valid_ratios, image_sizes, created_at, updated_at, deleted_at FROM app_generative_image_models
WHERE id = $1 AND deleted_at IS NULL AND is_active = TRUE
`

func (q *Queries) GetGenerativeImageModelByIdUser(ctx context.Context, id int64) (AppGenerativeImageModel, error) {
	row := q.db.QueryRowContext(ctx, getGenerativeImageModelByIdUser, id)
	var i AppGenerativeImageModel
	err := row.Scan(
		&i.ID,
		&i.Model,
		&i.Label,
		&i.Image,
		&i.Provider,
		&i.IsActive,
		pq.Array(&i.ValidRatios),
		pq.Array(&i.ImageSizes),
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGenerativeImageModelByModel = `-- name: GetGenerativeImageModelByModel :one
SELECT id, model, label, image, provider, is_active, valid_ratios, image_sizes, created_at, updated_at, deleted_at FROM app_generative_image_models
WHERE model = $1 AND deleted_at IS NULL
`

func (q *Queries) GetGenerativeImageModelByModel(ctx context.Context, model string) (AppGenerativeImageModel, error) {
	row := q.db.QueryRowContext(ctx, getGenerativeImageModelByModel, model)
	var i AppGenerativeImageModel
	err := row.Scan(
		&i.ID,
		&i.Model,
		&i.Label,
		&i.Image,
		&i.Provider,
		&i.IsActive,
		pq.Array(&i.ValidRatios),
		pq.Array(&i.ImageSizes),
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGenerativeImageModelByModelAdmin = `-- name: GetGenerativeImageModelByModelAdmin :one
SELECT id, model, label, image, provider, is_active, valid_ratios, image_sizes, created_at, updated_at, deleted_at FROM app_generative_image_models
WHERE model = $1 AND deleted_at IS NULL
`

func (q *Queries) GetGenerativeImageModelByModelAdmin(ctx context.Context, model string) (AppGenerativeImageModel, error) {
	row := q.db.QueryRowContext(ctx, getGenerativeImageModelByModelAdmin, model)
	var i AppGenerativeImageModel
	err := row.Scan(
		&i.ID,
		&i.Model,
		&i.Label,
		&i.Image,
		&i.Provider,
		&i.IsActive,
		pq.Array(&i.ValidRatios),
		pq.Array(&i.ImageSizes),
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGenerativeImageModelByModelUser = `-- name: GetGenerativeImageModelByModelUser :one
SELECT id, model, label, image, provider, is_active, valid_ratios, image_sizes, created_at, updated_at, deleted_at FROM app_generative_image_models
WHERE model = $1 AND deleted_at IS NULL AND is_active = TRUE
`

func (q *Queries) GetGenerativeImageModelByModelUser(ctx context.Context, model string) (AppGenerativeImageModel, error) {
	row := q.db.QueryRowContext(ctx, getGenerativeImageModelByModelUser, model)
	var i AppGenerativeImageModel
	err := row.Scan(
		&i.ID,
		&i.Model,
		&i.Label,
		&i.Image,
		&i.Provider,
		&i.IsActive,
		pq.Array(&i.ValidRatios),
		pq.Array(&i.ImageSizes),
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteGenerativeImageModel = `-- name: SoftDeleteGenerativeImageModel :one
UPDATE app_generative_image_models
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, model, label, image, provider, is_active, valid_ratios, image_sizes, created_at, updated_at, deleted_at
`

func (q *Queries) SoftDeleteGenerativeImageModel(ctx context.Context, id int64) (AppGenerativeImageModel, error) {
	row := q.db.QueryRowContext(ctx, softDeleteGenerativeImageModel, id)
	var i AppGenerativeImageModel
	err := row.Scan(
		&i.ID,
		&i.Model,
		&i.Label,
		&i.Image,
		&i.Provider,
		&i.IsActive,
		pq.Array(&i.ValidRatios),
		pq.Array(&i.ImageSizes),
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateGenerativeImageModel = `-- name: UpdateGenerativeImageModel :one
UPDATE app_generative_image_models
SET
  model = $2,
  label = $3,
  image = $4,
  provider = $5,
  is_active = $6,
  valid_ratios = $7,
  image_sizes = $8
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, model, label, image, provider, is_active, valid_ratios, image_sizes, created_at, updated_at, deleted_at
`

type UpdateGenerativeImageModelParams struct {
	ID          int64                               `json:"id"`
	Model       string                              `json:"model"`
	Label       string                              `json:"label"`
	Image       sql.NullString                      `json:"image"`
	Provider    AppGenerativeImageModelProviderType `json:"provider"`
	IsActive    bool                                `json:"is_active"`
	ValidRatios []string                            `json:"valid_ratios"`
	ImageSizes  []string                            `json:"image_sizes"`
}

func (q *Queries) UpdateGenerativeImageModel(ctx context.Context, arg UpdateGenerativeImageModelParams) (AppGenerativeImageModel, error) {
	row := q.db.QueryRowContext(ctx, updateGenerativeImageModel,
		arg.ID,
		arg.Model,
		arg.Label,
		arg.Image,
		arg.Provider,
		arg.IsActive,
		pq.Array(arg.ValidRatios),
		pq.Array(arg.ImageSizes),
	)
	var i AppGenerativeImageModel
	err := row.Scan(
		&i.ID,
		&i.Model,
		&i.Label,
		&i.Image,
		&i.Provider,
		&i.IsActive,
		pq.Array(&i.ValidRatios),
		pq.Array(&i.ImageSizes),
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
