// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_rss_category.sql

package entity

import (
	"context"
)

const countAllRSSCategory = `-- name: CountAllRSSCategory :one
SELECT COUNT(*)::bigint AS total
FROM app_rss_categories c
WHERE
  c.deleted_at IS NULL
  AND (
    COALESCE($1, '') = ''
    OR c.name ILIKE ('%' || $1 || '%')
  )
`

func (q *Queries) CountAllRSSCategory(ctx context.Context, search interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllRSSCategory, search)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getAllRSSCategory = `-- name: GetAllRSSCategory :many
SELECT
  c.id, c.name, c.deleted_at, c.created_at, c.updated_at
FROM app_rss_categories c
WHERE
  c.deleted_at IS NULL
  AND (
    COALESCE($1, '') = ''
    OR c.name ILIKE ('%' || $1 || '%')
  )
ORDER BY
  -- name
  CASE WHEN $2 = 'name' AND $3 = 'asc'  THEN c.name END ASC,
  CASE WHEN $2 = 'name' AND $3 = 'desc' THEN c.name END DESC,

  -- created_at
  CASE WHEN $2 = 'created_at' AND $3 = 'asc'  THEN c.created_at END ASC,
  CASE WHEN $2 = 'created_at' AND $3 = 'desc' THEN c.created_at END DESC,

  -- updated_at
  CASE WHEN $2 = 'updated_at' AND $3 = 'asc'  THEN c.updated_at END ASC,
  CASE WHEN $2 = 'updated_at' AND $3 = 'desc' THEN c.updated_at END DESC,

  -- id
  CASE WHEN $2 = 'id' AND $3 = 'asc'  THEN c.id END ASC,
  CASE WHEN $2 = 'id' AND $3 = 'desc' THEN c.id END DESC,

  -- fallback stable order
  c.id DESC
LIMIT $5
OFFSET $4
`

type GetAllRSSCategoryParams struct {
	Search     interface{} `json:"search"`
	SortBy     interface{} `json:"sort_by"`
	SortDir    interface{} `json:"sort_dir"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

func (q *Queries) GetAllRSSCategory(ctx context.Context, arg GetAllRSSCategoryParams) ([]AppRssCategory, error) {
	rows, err := q.db.QueryContext(ctx, getAllRSSCategory,
		arg.Search,
		arg.SortBy,
		arg.SortDir,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppRssCategory
	for rows.Next() {
		var i AppRssCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
