// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_social_platform.sql

package entity

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countAllAppSocialPlatforms = `-- name: CountAllAppSocialPlatforms :one
SELECT COUNT(*)::bigint AS total
FROM app_social_platforms p
WHERE
    p.deleted_at IS NULL
    AND (
        $1::boolean = true
        OR p.is_active = true
    )
    AND (
        COALESCE($2, '') = ''
        OR p.name ILIKE ('%' || $2 || '%')
        OR p.platform_code::text ILIKE ('%' || $2 || '%')
    )
`

type CountAllAppSocialPlatformsParams struct {
	IncludeInactive bool        `json:"include_inactive"`
	Search          interface{} `json:"search"`
}

func (q *Queries) CountAllAppSocialPlatforms(ctx context.Context, arg CountAllAppSocialPlatformsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllAppSocialPlatforms, arg.IncludeInactive, arg.Search)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createAppSocialPlatform = `-- name: CreateAppSocialPlatform :one
INSERT INTO app_social_platforms (
    platform_code,
    logo,
    name,
    hint,
    is_active
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, platform_code, logo, name, hint, is_active, created_at, updated_at, deleted_at
`

type CreateAppSocialPlatformParams struct {
	PlatformCode SocialPlatformType `json:"platform_code"`
	Logo         sql.NullString     `json:"logo"`
	Name         string             `json:"name"`
	Hint         string             `json:"hint"`
	IsActive     bool               `json:"is_active"`
}

func (q *Queries) CreateAppSocialPlatform(ctx context.Context, arg CreateAppSocialPlatformParams) (AppSocialPlatform, error) {
	row := q.db.QueryRowContext(ctx, createAppSocialPlatform,
		arg.PlatformCode,
		arg.Logo,
		arg.Name,
		arg.Hint,
		arg.IsActive,
	)
	var i AppSocialPlatform
	err := row.Scan(
		&i.ID,
		&i.PlatformCode,
		&i.Logo,
		&i.Name,
		&i.Hint,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createAppSocialPlatformChange = `-- name: CreateAppSocialPlatformChange :one
INSERT INTO app_social_platform_changes (
    action,
    profile_id,
    social_platform_id,
    before_platform_code,
    before_logo,
    before_name,
    before_hint,
    before_is_active,
    after_platform_code,
    after_logo,
    after_name,
    after_hint,
    after_is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
) RETURNING id, action, profile_id, social_platform_id, before_platform_code, before_logo, before_name, before_hint, before_is_active, after_platform_code, after_logo, after_name, after_hint, after_is_active, created_at, updated_at, deleted_at
`

type CreateAppSocialPlatformChangeParams struct {
	Action             ActionChangeType   `json:"action"`
	ProfileID          uuid.UUID          `json:"profile_id"`
	SocialPlatformID   int64              `json:"social_platform_id"`
	BeforePlatformCode SocialPlatformType `json:"before_platform_code"`
	BeforeLogo         sql.NullString     `json:"before_logo"`
	BeforeName         string             `json:"before_name"`
	BeforeHint         string             `json:"before_hint"`
	BeforeIsActive     bool               `json:"before_is_active"`
	AfterPlatformCode  SocialPlatformType `json:"after_platform_code"`
	AfterLogo          sql.NullString     `json:"after_logo"`
	AfterName          string             `json:"after_name"`
	AfterHint          string             `json:"after_hint"`
	AfterIsActive      bool               `json:"after_is_active"`
}

func (q *Queries) CreateAppSocialPlatformChange(ctx context.Context, arg CreateAppSocialPlatformChangeParams) (AppSocialPlatformChange, error) {
	row := q.db.QueryRowContext(ctx, createAppSocialPlatformChange,
		arg.Action,
		arg.ProfileID,
		arg.SocialPlatformID,
		arg.BeforePlatformCode,
		arg.BeforeLogo,
		arg.BeforeName,
		arg.BeforeHint,
		arg.BeforeIsActive,
		arg.AfterPlatformCode,
		arg.AfterLogo,
		arg.AfterName,
		arg.AfterHint,
		arg.AfterIsActive,
	)
	var i AppSocialPlatformChange
	err := row.Scan(
		&i.ID,
		&i.Action,
		&i.ProfileID,
		&i.SocialPlatformID,
		&i.BeforePlatformCode,
		&i.BeforeLogo,
		&i.BeforeName,
		&i.BeforeHint,
		&i.BeforeIsActive,
		&i.AfterPlatformCode,
		&i.AfterLogo,
		&i.AfterName,
		&i.AfterHint,
		&i.AfterIsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteAppSocialPlatform = `-- name: DeleteAppSocialPlatform :one
UPDATE app_social_platforms
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, platform_code, logo, name, hint, is_active, created_at, updated_at, deleted_at
`

func (q *Queries) DeleteAppSocialPlatform(ctx context.Context, id int64) (AppSocialPlatform, error) {
	row := q.db.QueryRowContext(ctx, deleteAppSocialPlatform, id)
	var i AppSocialPlatform
	err := row.Scan(
		&i.ID,
		&i.PlatformCode,
		&i.Logo,
		&i.Name,
		&i.Hint,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAllAppSocialPlatforms = `-- name: GetAllAppSocialPlatforms :many
SELECT id, platform_code, logo, name, hint, is_active, created_at, updated_at, deleted_at FROM app_social_platforms p
WHERE
    p.deleted_at IS NULL
    AND (
        $1::boolean = true
        OR p.is_active = true
    )
    AND (
        COALESCE($2, '') = ''
        OR p.name ILIKE ('%' || $2 || '%')
        OR p.platform_code::text ILIKE ('%' || $2 || '%')
    )
ORDER BY
    CASE WHEN $3 = 'id' AND $4 = 'asc' THEN p.id END ASC,
    CASE WHEN $3 = 'id' AND $4 = 'desc' THEN p.id END DESC,
    CASE WHEN $3 = 'name' AND $4 = 'asc' THEN p.name END ASC,
    CASE WHEN $3 = 'name' AND $4 = 'desc' THEN p.name END DESC,
    CASE WHEN $3 = 'platform_code' AND $4 = 'asc' THEN p.platform_code END ASC,
    CASE WHEN $3 = 'platform_code' AND $4 = 'desc' THEN p.platform_code END DESC,
    CASE WHEN $3 = 'is_active' AND $4 = 'asc' THEN p.is_active END ASC,
    CASE WHEN $3 = 'is_active' AND $4 = 'desc' THEN p.is_active END DESC,
    p.id DESC
LIMIT $6
OFFSET $5
`

type GetAllAppSocialPlatformsParams struct {
	IncludeInactive bool        `json:"include_inactive"`
	Search          interface{} `json:"search"`
	SortBy          interface{} `json:"sort_by"`
	SortDir         interface{} `json:"sort_dir"`
	PageOffset      int32       `json:"page_offset"`
	PageLimit       int32       `json:"page_limit"`
}

func (q *Queries) GetAllAppSocialPlatforms(ctx context.Context, arg GetAllAppSocialPlatformsParams) ([]AppSocialPlatform, error) {
	rows, err := q.db.QueryContext(ctx, getAllAppSocialPlatforms,
		arg.IncludeInactive,
		arg.Search,
		arg.SortBy,
		arg.SortDir,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppSocialPlatform
	for rows.Next() {
		var i AppSocialPlatform
		if err := rows.Scan(
			&i.ID,
			&i.PlatformCode,
			&i.Logo,
			&i.Name,
			&i.Hint,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppSocialPlatformById = `-- name: GetAppSocialPlatformById :one
SELECT id, platform_code, logo, name, hint, is_active, created_at, updated_at, deleted_at FROM app_social_platforms
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAppSocialPlatformById(ctx context.Context, id int64) (AppSocialPlatform, error) {
	row := q.db.QueryRowContext(ctx, getAppSocialPlatformById, id)
	var i AppSocialPlatform
	err := row.Scan(
		&i.ID,
		&i.PlatformCode,
		&i.Logo,
		&i.Name,
		&i.Hint,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAppSocialPlatformByPlatformCode = `-- name: GetAppSocialPlatformByPlatformCode :one
SELECT id, platform_code, logo, name, hint, is_active, created_at, updated_at, deleted_at FROM app_social_platforms
WHERE platform_code = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAppSocialPlatformByPlatformCode(ctx context.Context, platformCode SocialPlatformType) (AppSocialPlatform, error) {
	row := q.db.QueryRowContext(ctx, getAppSocialPlatformByPlatformCode, platformCode)
	var i AppSocialPlatform
	err := row.Scan(
		&i.ID,
		&i.PlatformCode,
		&i.Logo,
		&i.Name,
		&i.Hint,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateAppSocialPlatform = `-- name: UpdateAppSocialPlatform :one
UPDATE app_social_platforms
SET
    platform_code = $2,
    logo = $3,
    name = $4,
    hint = $5,
    is_active = $6
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, platform_code, logo, name, hint, is_active, created_at, updated_at, deleted_at
`

type UpdateAppSocialPlatformParams struct {
	ID           int64              `json:"id"`
	PlatformCode SocialPlatformType `json:"platform_code"`
	Logo         sql.NullString     `json:"logo"`
	Name         string             `json:"name"`
	Hint         string             `json:"hint"`
	IsActive     bool               `json:"is_active"`
}

func (q *Queries) UpdateAppSocialPlatform(ctx context.Context, arg UpdateAppSocialPlatformParams) (AppSocialPlatform, error) {
	row := q.db.QueryRowContext(ctx, updateAppSocialPlatform,
		arg.ID,
		arg.PlatformCode,
		arg.Logo,
		arg.Name,
		arg.Hint,
		arg.IsActive,
	)
	var i AppSocialPlatform
	err := row.Scan(
		&i.ID,
		&i.PlatformCode,
		&i.Logo,
		&i.Name,
		&i.Hint,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
