// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_payment_method.sql

package entity

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countAllPaymentMethods = `-- name: CountAllPaymentMethods :one
SELECT COUNT(*)::bigint AS total
FROM app_payment_methods p
WHERE
  p.deleted_at IS NULL
  AND (
    COALESCE($1, '') = ''
    OR p.name ILIKE ('%' || $1 || '%')
    OR p.code ILIKE ('%' || $1 || '%')
  )
  AND (
    $2::boolean = TRUE
    OR p.is_active = TRUE
  )
`

type CountAllPaymentMethodsParams struct {
	Search  interface{} `json:"search"`
	IsAdmin bool        `json:"is_admin"`
}

func (q *Queries) CountAllPaymentMethods(ctx context.Context, arg CountAllPaymentMethodsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllPaymentMethods, arg.Search, arg.IsAdmin)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createPaymentMethod = `-- name: CreatePaymentMethod :one
INSERT INTO app_payment_methods (
  code,
  name,
  type,
  image,
  tax_fee,
  admin_type,
  admin_fee,
  is_active
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, code, name, type, image, tax_fee, admin_type, admin_fee, is_active, created_at, updated_at, deleted_at
`

type CreatePaymentMethodParams struct {
	Code      string               `json:"code"`
	Name      string               `json:"name"`
	Type      AppPaymentMethodType `json:"type"`
	Image     sql.NullString       `json:"image"`
	TaxFee    int64                `json:"tax_fee"`
	AdminType AppPaymentAdminType  `json:"admin_type"`
	AdminFee  int64                `json:"admin_fee"`
	IsActive  bool                 `json:"is_active"`
}

func (q *Queries) CreatePaymentMethod(ctx context.Context, arg CreatePaymentMethodParams) (AppPaymentMethod, error) {
	row := q.db.QueryRowContext(ctx, createPaymentMethod,
		arg.Code,
		arg.Name,
		arg.Type,
		arg.Image,
		arg.TaxFee,
		arg.AdminType,
		arg.AdminFee,
		arg.IsActive,
	)
	var i AppPaymentMethod
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Image,
		&i.TaxFee,
		&i.AdminType,
		&i.AdminFee,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createPaymentMethodChange = `-- name: CreatePaymentMethodChange :one
INSERT INTO app_payment_method_changes (
  action,
  profile_id,
  payment_method_id,
  before_code,
  before_name,
  before_type,
  before_image,
  before_admin_type,
  before_admin_fee,
  before_tax_fee,
  before_is_active,
  after_code,
  after_name,
  after_type,
  after_image,
  after_admin_type,
  after_admin_fee,
  after_tax_fee,
  after_is_active
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19
) RETURNING id, action, profile_id, payment_method_id, before_code, before_name, before_type, before_image, before_admin_type, before_admin_fee, before_tax_fee, before_is_active, after_code, after_name, after_type, after_image, after_admin_type, after_admin_fee, after_tax_fee, after_is_active, created_at, updated_at, deleted_at
`

type CreatePaymentMethodChangeParams struct {
	Action          ActionChangeType     `json:"action"`
	ProfileID       uuid.UUID            `json:"profile_id"`
	PaymentMethodID int64                `json:"payment_method_id"`
	BeforeCode      string               `json:"before_code"`
	BeforeName      string               `json:"before_name"`
	BeforeType      AppPaymentMethodType `json:"before_type"`
	BeforeImage     sql.NullString       `json:"before_image"`
	BeforeAdminType AppPaymentAdminType  `json:"before_admin_type"`
	BeforeAdminFee  int64                `json:"before_admin_fee"`
	BeforeTaxFee    int64                `json:"before_tax_fee"`
	BeforeIsActive  bool                 `json:"before_is_active"`
	AfterCode       string               `json:"after_code"`
	AfterName       string               `json:"after_name"`
	AfterType       AppPaymentMethodType `json:"after_type"`
	AfterImage      sql.NullString       `json:"after_image"`
	AfterAdminType  AppPaymentAdminType  `json:"after_admin_type"`
	AfterAdminFee   int64                `json:"after_admin_fee"`
	AfterTaxFee     int64                `json:"after_tax_fee"`
	AfterIsActive   bool                 `json:"after_is_active"`
}

func (q *Queries) CreatePaymentMethodChange(ctx context.Context, arg CreatePaymentMethodChangeParams) (AppPaymentMethodChange, error) {
	row := q.db.QueryRowContext(ctx, createPaymentMethodChange,
		arg.Action,
		arg.ProfileID,
		arg.PaymentMethodID,
		arg.BeforeCode,
		arg.BeforeName,
		arg.BeforeType,
		arg.BeforeImage,
		arg.BeforeAdminType,
		arg.BeforeAdminFee,
		arg.BeforeTaxFee,
		arg.BeforeIsActive,
		arg.AfterCode,
		arg.AfterName,
		arg.AfterType,
		arg.AfterImage,
		arg.AfterAdminType,
		arg.AfterAdminFee,
		arg.AfterTaxFee,
		arg.AfterIsActive,
	)
	var i AppPaymentMethodChange
	err := row.Scan(
		&i.ID,
		&i.Action,
		&i.ProfileID,
		&i.PaymentMethodID,
		&i.BeforeCode,
		&i.BeforeName,
		&i.BeforeType,
		&i.BeforeImage,
		&i.BeforeAdminType,
		&i.BeforeAdminFee,
		&i.BeforeTaxFee,
		&i.BeforeIsActive,
		&i.AfterCode,
		&i.AfterName,
		&i.AfterType,
		&i.AfterImage,
		&i.AfterAdminType,
		&i.AfterAdminFee,
		&i.AfterTaxFee,
		&i.AfterIsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAllPaymentMethods = `-- name: GetAllPaymentMethods :many
SELECT
  p.id, p.code, p.name, p.type, p.image, p.tax_fee, p.admin_type, p.admin_fee, p.is_active, p.created_at, p.updated_at, p.deleted_at
FROM app_payment_methods p
WHERE
  p.deleted_at IS NULL
  AND (
    COALESCE($1, '') = ''
    OR p.name ILIKE ('%' || $1 || '%')
    OR p.code ILIKE ('%' || $1 || '%')
  )
  AND (
    $2::boolean = TRUE
    OR p.is_active = TRUE
  )
ORDER BY
  -- name
  CASE WHEN $3 = 'name' AND $4 = 'asc'  THEN p.name END ASC,
  CASE WHEN $3 = 'name' AND $4 = 'desc' THEN p.name END DESC,

  -- code
  CASE WHEN $3 = 'code' AND $4 = 'asc'  THEN p.code END ASC,
  CASE WHEN $3 = 'code' AND $4 = 'desc' THEN p.code END DESC,

  -- created_at
  CASE WHEN $3 = 'created_at' AND $4 = 'asc'  THEN p.created_at END ASC,
  CASE WHEN $3 = 'created_at' AND $4 = 'desc' THEN p.created_at END DESC,

  -- updated_at
  CASE WHEN $3 = 'updated_at' AND $4 = 'asc'  THEN p.updated_at END ASC,
  CASE WHEN $3 = 'updated_at' AND $4 = 'desc' THEN p.updated_at END DESC,

  -- id
  CASE WHEN $3 = 'id' AND $4 = 'asc'  THEN p.id END ASC,
  CASE WHEN $3 = 'id' AND $4 = 'desc' THEN p.id END DESC,

  -- fallback stable order
  p.id DESC
LIMIT $6
OFFSET $5
`

type GetAllPaymentMethodsParams struct {
	Search     interface{} `json:"search"`
	IsAdmin    bool        `json:"is_admin"`
	SortBy     interface{} `json:"sort_by"`
	SortDir    interface{} `json:"sort_dir"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

func (q *Queries) GetAllPaymentMethods(ctx context.Context, arg GetAllPaymentMethodsParams) ([]AppPaymentMethod, error) {
	rows, err := q.db.QueryContext(ctx, getAllPaymentMethods,
		arg.Search,
		arg.IsAdmin,
		arg.SortBy,
		arg.SortDir,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppPaymentMethod
	for rows.Next() {
		var i AppPaymentMethod
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Type,
			&i.Image,
			&i.TaxFee,
			&i.AdminType,
			&i.AdminFee,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentMethodByCode = `-- name: GetPaymentMethodByCode :one
SELECT id, code, name, type, image, tax_fee, admin_type, admin_fee, is_active, created_at, updated_at, deleted_at FROM app_payment_methods
WHERE code = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPaymentMethodByCode(ctx context.Context, code string) (AppPaymentMethod, error) {
	row := q.db.QueryRowContext(ctx, getPaymentMethodByCode, code)
	var i AppPaymentMethod
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Image,
		&i.TaxFee,
		&i.AdminType,
		&i.AdminFee,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPaymentMethodByCodeAdmin = `-- name: GetPaymentMethodByCodeAdmin :one
SELECT id, code, name, type, image, tax_fee, admin_type, admin_fee, is_active, created_at, updated_at, deleted_at FROM app_payment_methods
WHERE code = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPaymentMethodByCodeAdmin(ctx context.Context, code string) (AppPaymentMethod, error) {
	row := q.db.QueryRowContext(ctx, getPaymentMethodByCodeAdmin, code)
	var i AppPaymentMethod
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Image,
		&i.TaxFee,
		&i.AdminType,
		&i.AdminFee,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPaymentMethodByCodeUser = `-- name: GetPaymentMethodByCodeUser :one
SELECT id, code, name, type, image, tax_fee, admin_type, admin_fee, is_active, created_at, updated_at, deleted_at FROM app_payment_methods
WHERE code = $1 AND deleted_at IS NULL AND is_active = TRUE
`

func (q *Queries) GetPaymentMethodByCodeUser(ctx context.Context, code string) (AppPaymentMethod, error) {
	row := q.db.QueryRowContext(ctx, getPaymentMethodByCodeUser, code)
	var i AppPaymentMethod
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Image,
		&i.TaxFee,
		&i.AdminType,
		&i.AdminFee,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPaymentMethodById = `-- name: GetPaymentMethodById :one
SELECT id, code, name, type, image, tax_fee, admin_type, admin_fee, is_active, created_at, updated_at, deleted_at FROM app_payment_methods
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPaymentMethodById(ctx context.Context, id int64) (AppPaymentMethod, error) {
	row := q.db.QueryRowContext(ctx, getPaymentMethodById, id)
	var i AppPaymentMethod
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Image,
		&i.TaxFee,
		&i.AdminType,
		&i.AdminFee,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPaymentMethodByIdAdmin = `-- name: GetPaymentMethodByIdAdmin :one
SELECT id, code, name, type, image, tax_fee, admin_type, admin_fee, is_active, created_at, updated_at, deleted_at FROM app_payment_methods
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPaymentMethodByIdAdmin(ctx context.Context, id int64) (AppPaymentMethod, error) {
	row := q.db.QueryRowContext(ctx, getPaymentMethodByIdAdmin, id)
	var i AppPaymentMethod
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Image,
		&i.TaxFee,
		&i.AdminType,
		&i.AdminFee,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPaymentMethodByIdUser = `-- name: GetPaymentMethodByIdUser :one
SELECT id, code, name, type, image, tax_fee, admin_type, admin_fee, is_active, created_at, updated_at, deleted_at FROM app_payment_methods
WHERE id = $1 AND deleted_at IS NULL AND is_active = TRUE
`

func (q *Queries) GetPaymentMethodByIdUser(ctx context.Context, id int64) (AppPaymentMethod, error) {
	row := q.db.QueryRowContext(ctx, getPaymentMethodByIdUser, id)
	var i AppPaymentMethod
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Image,
		&i.TaxFee,
		&i.AdminType,
		&i.AdminFee,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeletePaymentMethod = `-- name: SoftDeletePaymentMethod :one
UPDATE app_payment_methods
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, code, name, type, image, tax_fee, admin_type, admin_fee, is_active, created_at, updated_at, deleted_at
`

func (q *Queries) SoftDeletePaymentMethod(ctx context.Context, id int64) (AppPaymentMethod, error) {
	row := q.db.QueryRowContext(ctx, softDeletePaymentMethod, id)
	var i AppPaymentMethod
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Image,
		&i.TaxFee,
		&i.AdminType,
		&i.AdminFee,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updatePaymentMethod = `-- name: UpdatePaymentMethod :one
UPDATE app_payment_methods
SET
  code = $2,
  name = $3,
  type = $4,
  image = $5,
  tax_fee = $6,
  admin_type = $7,
  admin_fee = $8,
  is_active = $9
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, code, name, type, image, tax_fee, admin_type, admin_fee, is_active, created_at, updated_at, deleted_at
`

type UpdatePaymentMethodParams struct {
	ID        int64                `json:"id"`
	Code      string               `json:"code"`
	Name      string               `json:"name"`
	Type      AppPaymentMethodType `json:"type"`
	Image     sql.NullString       `json:"image"`
	TaxFee    int64                `json:"tax_fee"`
	AdminType AppPaymentAdminType  `json:"admin_type"`
	AdminFee  int64                `json:"admin_fee"`
	IsActive  bool                 `json:"is_active"`
}

func (q *Queries) UpdatePaymentMethod(ctx context.Context, arg UpdatePaymentMethodParams) (AppPaymentMethod, error) {
	row := q.db.QueryRowContext(ctx, updatePaymentMethod,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Type,
		arg.Image,
		arg.TaxFee,
		arg.AdminType,
		arg.AdminFee,
		arg.IsActive,
	)
	var i AppPaymentMethod
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Image,
		&i.TaxFee,
		&i.AdminType,
		&i.AdminFee,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
