// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_token_product.sql

package entity

import (
	"context"
)

const getAppTokenProductByTypeCurrency = `-- name: GetAppTokenProductByTypeCurrency :one
SELECT id, token_type, currency_code, price_amount, token_amount, is_active, sort_order, created_at, updated_at, deleted_at
FROM app_token_products
WHERE token_type = $1
  AND currency_code = $2
  AND is_active = TRUE
  AND deleted_at IS NULL
ORDER BY sort_order ASC, created_at DESC
LIMIT 1
`

type GetAppTokenProductByTypeCurrencyParams struct {
	TokenType    TokenType `json:"token_type"`
	CurrencyCode string    `json:"currency_code"`
}

func (q *Queries) GetAppTokenProductByTypeCurrency(ctx context.Context, arg GetAppTokenProductByTypeCurrencyParams) (AppTokenProduct, error) {
	row := q.db.QueryRowContext(ctx, getAppTokenProductByTypeCurrency, arg.TokenType, arg.CurrencyCode)
	var i AppTokenProduct
	err := row.Scan(
		&i.ID,
		&i.TokenType,
		&i.CurrencyCode,
		&i.PriceAmount,
		&i.TokenAmount,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
