// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: business_saved_template_creator_image.sql

package entity

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const checkSavedCreatorImageExists = `-- name: CheckSavedCreatorImageExists :one
SELECT EXISTS (
    SELECT 1 FROM business_saved_template_creator_images
    WHERE business_root_id = $1
      AND creator_image_id = $2
      AND deleted_at IS NULL
) AS exists
`

type CheckSavedCreatorImageExistsParams struct {
	BusinessRootID int64 `json:"business_root_id"`
	CreatorImageID int64 `json:"creator_image_id"`
}

func (q *Queries) CheckSavedCreatorImageExists(ctx context.Context, arg CheckSavedCreatorImageExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkSavedCreatorImageExists, arg.BusinessRootID, arg.CreatorImageID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countSavedCreatorImageByBusinessId = `-- name: CountSavedCreatorImageByBusinessId :one
SELECT COUNT(*)
FROM business_saved_template_creator_images bstci
JOIN creator_images ci ON ci.id = bstci.creator_image_id
WHERE bstci.business_root_id = $1
  AND bstci.deleted_at IS NULL
  AND ($2::TEXT IS NULL OR ci.name ILIKE '%' || $2::TEXT || '%')
  AND ($3::TIMESTAMPTZ IS NULL OR bstci.created_at >= $3::TIMESTAMPTZ)
  AND ($4::TIMESTAMPTZ IS NULL OR bstci.created_at <= $4::TIMESTAMPTZ)
  AND ($5::BIGINT IS NULL OR EXISTS (
      SELECT 1 FROM creator_image_type_categories citc
      WHERE citc.creator_image_id = ci.id AND citc.type_category_id = $5::BIGINT
  ))
  AND ($6::BIGINT IS NULL OR EXISTS (
      SELECT 1 FROM creator_image_product_categories cipc
      WHERE cipc.creator_image_id = ci.id AND cipc.product_category_id = $6::BIGINT
  ))
`

type CountSavedCreatorImageByBusinessIdParams struct {
	BusinessRootID    int64          `json:"business_root_id"`
	Search            sql.NullString `json:"search"`
	DateStart         sql.NullTime   `json:"date_start"`
	DateEnd           sql.NullTime   `json:"date_end"`
	TypeCategoryID    sql.NullInt64  `json:"type_category_id"`
	ProductCategoryID sql.NullInt64  `json:"product_category_id"`
}

func (q *Queries) CountSavedCreatorImageByBusinessId(ctx context.Context, arg CountSavedCreatorImageByBusinessIdParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSavedCreatorImageByBusinessId,
		arg.BusinessRootID,
		arg.Search,
		arg.DateStart,
		arg.DateEnd,
		arg.TypeCategoryID,
		arg.ProductCategoryID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSavedCreatorImage = `-- name: CreateSavedCreatorImage :one
INSERT INTO business_saved_template_creator_images (
    business_root_id,
    creator_image_id
) VALUES (
    $1,
    $2
) RETURNING id, business_root_id, creator_image_id, created_at, updated_at, deleted_at
`

type CreateSavedCreatorImageParams struct {
	BusinessRootID int64 `json:"business_root_id"`
	CreatorImageID int64 `json:"creator_image_id"`
}

func (q *Queries) CreateSavedCreatorImage(ctx context.Context, arg CreateSavedCreatorImageParams) (BusinessSavedTemplateCreatorImage, error) {
	row := q.db.QueryRowContext(ctx, createSavedCreatorImage, arg.BusinessRootID, arg.CreatorImageID)
	var i BusinessSavedTemplateCreatorImage
	err := row.Scan(
		&i.ID,
		&i.BusinessRootID,
		&i.CreatorImageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAllSavedCreatorImageByBusinessId = `-- name: GetAllSavedCreatorImageByBusinessId :many

SELECT
    bstci.id,
    bstci.business_root_id,
    bstci.creator_image_id,
    bstci.created_at AS saved_at,
    ci.name,
    ci.image_url,
    ci.is_published,
    ci.is_banned,
    ci.banned_reason,
    ci.price,
    ci.profile_id AS publisher_id,
    p.name AS publisher_name,
    p.image_url AS publisher_image,
    ci.created_at,
    ci.updated_at,
    ci.deleted_at AS creator_image_deleted_at,
    -- type categories as JSON array
    COALESCE(
        (SELECT json_agg(json_build_object('id', tc.id, 'name', tc.name))
         FROM creator_image_type_categories citc
         JOIN app_creator_image_type_categories tc ON tc.id = citc.type_category_id
         WHERE citc.creator_image_id = ci.id),
        '[]'::json
    ) AS type_category_subs,
    -- product categories as JSON array
    COALESCE(
        (SELECT json_agg(json_build_object('id', pc.id, 'name', pc.indonesian_name))
         FROM creator_image_product_categories cipc
         JOIN app_creator_image_product_categories pc ON pc.id = cipc.product_category_id
         WHERE cipc.creator_image_id = ci.id),
        '[]'::json
    ) AS product_category_subs
FROM business_saved_template_creator_images bstci
JOIN creator_images ci ON ci.id = bstci.creator_image_id
LEFT JOIN profiles p ON p.id = ci.profile_id
WHERE bstci.business_root_id = $1
  AND bstci.deleted_at IS NULL
  -- search by name
  AND ($2::TEXT IS NULL OR ci.name ILIKE '%' || $2::TEXT || '%')
  -- filter by date range (on saved_at)
  AND ($3::TIMESTAMPTZ IS NULL OR bstci.created_at >= $3::TIMESTAMPTZ)
  AND ($4::TIMESTAMPTZ IS NULL OR bstci.created_at <= $4::TIMESTAMPTZ)
  -- filter by type category
  AND ($5::BIGINT IS NULL OR EXISTS (
      SELECT 1 FROM creator_image_type_categories citc
      WHERE citc.creator_image_id = ci.id AND citc.type_category_id = $5::BIGINT
  ))
  -- filter by product category
  AND ($6::BIGINT IS NULL OR EXISTS (
      SELECT 1 FROM creator_image_product_categories cipc
      WHERE cipc.creator_image_id = ci.id AND cipc.product_category_id = $6::BIGINT
  ))
ORDER BY
    CASE WHEN $7::TEXT = 'id' AND $8::TEXT = 'asc' THEN bstci.id END ASC,
    CASE WHEN $7::TEXT = 'id' AND $8::TEXT = 'desc' THEN bstci.id END DESC,
    CASE WHEN $7::TEXT = 'created_at' AND $8::TEXT = 'asc' THEN bstci.created_at END ASC,
    CASE WHEN $7::TEXT = 'created_at' AND $8::TEXT = 'desc' THEN bstci.created_at END DESC,
    CASE WHEN $7::TEXT = 'updated_at' AND $8::TEXT = 'asc' THEN bstci.updated_at END ASC,
    CASE WHEN $7::TEXT = 'updated_at' AND $8::TEXT = 'desc' THEN bstci.updated_at END DESC,
    CASE WHEN $7::TEXT = 'name' AND $8::TEXT = 'asc' THEN ci.name END ASC,
    CASE WHEN $7::TEXT = 'name' AND $8::TEXT = 'desc' THEN ci.name END DESC,
    bstci.id DESC -- default sort
LIMIT $10 OFFSET $9
`

type GetAllSavedCreatorImageByBusinessIdParams struct {
	BusinessRootID    int64          `json:"business_root_id"`
	Search            sql.NullString `json:"search"`
	DateStart         sql.NullTime   `json:"date_start"`
	DateEnd           sql.NullTime   `json:"date_end"`
	TypeCategoryID    sql.NullInt64  `json:"type_category_id"`
	ProductCategoryID sql.NullInt64  `json:"product_category_id"`
	SortBy            sql.NullString `json:"sort_by"`
	SortDir           sql.NullString `json:"sort_dir"`
	PageOffset        int32          `json:"page_offset"`
	PageLimit         int32          `json:"page_limit"`
}

type GetAllSavedCreatorImageByBusinessIdRow struct {
	ID                    int64          `json:"id"`
	BusinessRootID        int64          `json:"business_root_id"`
	CreatorImageID        int64          `json:"creator_image_id"`
	SavedAt               time.Time      `json:"saved_at"`
	Name                  string         `json:"name"`
	ImageUrl              string         `json:"image_url"`
	IsPublished           bool           `json:"is_published"`
	IsBanned              bool           `json:"is_banned"`
	BannedReason          sql.NullString `json:"banned_reason"`
	Price                 int64          `json:"price"`
	PublisherID           uuid.NullUUID  `json:"publisher_id"`
	PublisherName         sql.NullString `json:"publisher_name"`
	PublisherImage        sql.NullString `json:"publisher_image"`
	CreatedAt             sql.NullTime   `json:"created_at"`
	UpdatedAt             sql.NullTime   `json:"updated_at"`
	CreatorImageDeletedAt sql.NullTime   `json:"creator_image_deleted_at"`
	TypeCategorySubs      interface{}    `json:"type_category_subs"`
	ProductCategorySubs   interface{}    `json:"product_category_subs"`
}

// internal/repository/queries/business_saved_template_creator_image.sql
func (q *Queries) GetAllSavedCreatorImageByBusinessId(ctx context.Context, arg GetAllSavedCreatorImageByBusinessIdParams) ([]GetAllSavedCreatorImageByBusinessIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllSavedCreatorImageByBusinessId,
		arg.BusinessRootID,
		arg.Search,
		arg.DateStart,
		arg.DateEnd,
		arg.TypeCategoryID,
		arg.ProductCategoryID,
		arg.SortBy,
		arg.SortDir,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllSavedCreatorImageByBusinessIdRow
	for rows.Next() {
		var i GetAllSavedCreatorImageByBusinessIdRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessRootID,
			&i.CreatorImageID,
			&i.SavedAt,
			&i.Name,
			&i.ImageUrl,
			&i.IsPublished,
			&i.IsBanned,
			&i.BannedReason,
			&i.Price,
			&i.PublisherID,
			&i.PublisherName,
			&i.PublisherImage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorImageDeletedAt,
			&i.TypeCategorySubs,
			&i.ProductCategorySubs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSavedCreatorImageByBusinessAndCreatorImage = `-- name: GetSavedCreatorImageByBusinessAndCreatorImage :one
SELECT id, business_root_id, creator_image_id, created_at, updated_at, deleted_at FROM business_saved_template_creator_images
WHERE business_root_id = $1
  AND creator_image_id = $2
  AND deleted_at IS NULL
`

type GetSavedCreatorImageByBusinessAndCreatorImageParams struct {
	BusinessRootID int64 `json:"business_root_id"`
	CreatorImageID int64 `json:"creator_image_id"`
}

func (q *Queries) GetSavedCreatorImageByBusinessAndCreatorImage(ctx context.Context, arg GetSavedCreatorImageByBusinessAndCreatorImageParams) (BusinessSavedTemplateCreatorImage, error) {
	row := q.db.QueryRowContext(ctx, getSavedCreatorImageByBusinessAndCreatorImage, arg.BusinessRootID, arg.CreatorImageID)
	var i BusinessSavedTemplateCreatorImage
	err := row.Scan(
		&i.ID,
		&i.BusinessRootID,
		&i.CreatorImageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteSavedCreatorImage = `-- name: SoftDeleteSavedCreatorImage :exec
UPDATE business_saved_template_creator_images
SET deleted_at = NOW()
WHERE business_root_id = $1
  AND creator_image_id = $2
  AND deleted_at IS NULL
`

type SoftDeleteSavedCreatorImageParams struct {
	BusinessRootID int64 `json:"business_root_id"`
	CreatorImageID int64 `json:"creator_image_id"`
}

func (q *Queries) SoftDeleteSavedCreatorImage(ctx context.Context, arg SoftDeleteSavedCreatorImageParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteSavedCreatorImage, arg.BusinessRootID, arg.CreatorImageID)
	return err
}
