// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: business_member.sql

package entity

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createBusinessMember = `-- name: CreateBusinessMember :one
INSERT INTO business_members (
	status,
	role,
	answered_at,
	business_root_id,
	profile_id
)
VALUES (
	$1,
	$2,
	$3,
	$4,
	$5
)
RETURNING id, status, role, answered_at, business_root_id, profile_id, created_at, updated_at
`

type CreateBusinessMemberParams struct {
	Status         BusinessMemberStatus `json:"status"`
	Role           BusinessMemberRole   `json:"role"`
	AnsweredAt     sql.NullTime         `json:"answered_at"`
	BusinessRootID uuid.UUID            `json:"business_root_id"`
	ProfileID      uuid.UUID            `json:"profile_id"`
}

func (q *Queries) CreateBusinessMember(ctx context.Context, arg CreateBusinessMemberParams) (BusinessMember, error) {
	row := q.db.QueryRowContext(ctx, createBusinessMember,
		arg.Status,
		arg.Role,
		arg.AnsweredAt,
		arg.BusinessRootID,
		arg.ProfileID,
	)
	var i BusinessMember
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Role,
		&i.AnsweredAt,
		&i.BusinessRootID,
		&i.ProfileID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
