// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: business_knowledge.sql

package entity

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createBusinessKnowledge = `-- name: CreateBusinessKnowledge :one
INSERT INTO business_knowledges (
    name,
    primary_logo_url,
    category,
    description,
    unique_selling_point,
    website_url,
    vision_mission,
    location,
    color_tone,
    business_root_id
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, name, primary_logo_url, category, description, unique_selling_point, website_url, vision_mission, location, color_tone, business_root_id, created_at, updated_at, deleted_at
`

type CreateBusinessKnowledgeParams struct {
	Name               string         `json:"name"`
	PrimaryLogoUrl     sql.NullString `json:"primary_logo_url"`
	Category           string         `json:"category"`
	Description        sql.NullString `json:"description"`
	UniqueSellingPoint sql.NullString `json:"unique_selling_point"`
	WebsiteUrl         sql.NullString `json:"website_url"`
	VisionMission      sql.NullString `json:"vision_mission"`
	Location           sql.NullString `json:"location"`
	ColorTone          sql.NullString `json:"color_tone"`
	BusinessRootID     uuid.UUID      `json:"business_root_id"`
}

func (q *Queries) CreateBusinessKnowledge(ctx context.Context, arg CreateBusinessKnowledgeParams) (BusinessKnowledge, error) {
	row := q.db.QueryRowContext(ctx, createBusinessKnowledge,
		arg.Name,
		arg.PrimaryLogoUrl,
		arg.Category,
		arg.Description,
		arg.UniqueSellingPoint,
		arg.WebsiteUrl,
		arg.VisionMission,
		arg.Location,
		arg.ColorTone,
		arg.BusinessRootID,
	)
	var i BusinessKnowledge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PrimaryLogoUrl,
		&i.Category,
		&i.Description,
		&i.UniqueSellingPoint,
		&i.WebsiteUrl,
		&i.VisionMission,
		&i.Location,
		&i.ColorTone,
		&i.BusinessRootID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBusinessKnowledgeByBusinessRootID = `-- name: GetBusinessKnowledgeByBusinessRootID :one
SELECT root.id AS business_root_id, kn.name, kn.primary_logo_url, kn.category, kn.description, kn.color_tone, root.created_at, root.updated_at
FROM business_knowledges kn
JOIN business_roots root ON kn.business_root_id = root.id
WHERE root.id = $1 AND root.deleted_at IS NULL AND kn.deleted_at IS NULL
`

type GetBusinessKnowledgeByBusinessRootIDRow struct {
	BusinessRootID uuid.UUID      `json:"business_root_id"`
	Name           string         `json:"name"`
	PrimaryLogoUrl sql.NullString `json:"primary_logo_url"`
	Category       string         `json:"category"`
	Description    sql.NullString `json:"description"`
	ColorTone      sql.NullString `json:"color_tone"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

func (q *Queries) GetBusinessKnowledgeByBusinessRootID(ctx context.Context, businessRootID uuid.UUID) (GetBusinessKnowledgeByBusinessRootIDRow, error) {
	row := q.db.QueryRowContext(ctx, getBusinessKnowledgeByBusinessRootID, businessRootID)
	var i GetBusinessKnowledgeByBusinessRootIDRow
	err := row.Scan(
		&i.BusinessRootID,
		&i.Name,
		&i.PrimaryLogoUrl,
		&i.Category,
		&i.Description,
		&i.ColorTone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteBusinessKnowledgeByBusinessRootID = `-- name: SoftDeleteBusinessKnowledgeByBusinessRootID :one
UPDATE business_knowledges
SET deleted_at = NOW()
WHERE business_root_id = $1
RETURNING id
`

func (q *Queries) SoftDeleteBusinessKnowledgeByBusinessRootID(ctx context.Context, businessRootID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, softDeleteBusinessKnowledgeByBusinessRootID, businessRootID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
