// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: business_knowledge.sql

package entity

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createBusinessKnowledge = `-- name: CreateBusinessKnowledge :one
INSERT INTO business_knowledges (
    name,
    primary_logo_url,
    category,
    description,
    unique_selling_point,
    website_url,
    vision_mission,
    location,
    color_tone,
    business_root_id
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, name, primary_logo_url, category, description, unique_selling_point, website_url, vision_mission, location, color_tone, business_root_id, created_at, updated_at, deleted_at
`

type CreateBusinessKnowledgeParams struct {
	Name               string         `json:"name"`
	PrimaryLogoUrl     sql.NullString `json:"primary_logo_url"`
	Category           string         `json:"category"`
	Description        sql.NullString `json:"description"`
	UniqueSellingPoint sql.NullString `json:"unique_selling_point"`
	WebsiteUrl         sql.NullString `json:"website_url"`
	VisionMission      sql.NullString `json:"vision_mission"`
	Location           sql.NullString `json:"location"`
	ColorTone          sql.NullString `json:"color_tone"`
	BusinessRootID     uuid.UUID      `json:"business_root_id"`
}

func (q *Queries) CreateBusinessKnowledge(ctx context.Context, arg CreateBusinessKnowledgeParams) (BusinessKnowledge, error) {
	row := q.db.QueryRowContext(ctx, createBusinessKnowledge,
		arg.Name,
		arg.PrimaryLogoUrl,
		arg.Category,
		arg.Description,
		arg.UniqueSellingPoint,
		arg.WebsiteUrl,
		arg.VisionMission,
		arg.Location,
		arg.ColorTone,
		arg.BusinessRootID,
	)
	var i BusinessKnowledge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PrimaryLogoUrl,
		&i.Category,
		&i.Description,
		&i.UniqueSellingPoint,
		&i.WebsiteUrl,
		&i.VisionMission,
		&i.Location,
		&i.ColorTone,
		&i.BusinessRootID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
