// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: business_root.sql

package entity

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countJoinedBusinessesByProfileID = `-- name: CountJoinedBusinessesByProfileID :one
SELECT COUNT(*)::bigint AS total
FROM business_members bm
JOIN business_roots br
  ON br.id = bm.business_root_id
JOIN business_knowledges bk
  ON bk.business_root_id = br.id
WHERE
  bm.profile_id = $1
  AND bm.status = 'accepted'
  AND bk.deleted_at IS NULL
  AND (
    COALESCE($2, '') = ''
    OR bk.name ILIKE ('%' || $2 || '%')
  )
`

type CountJoinedBusinessesByProfileIDParams struct {
	ProfileID uuid.UUID   `json:"profile_id"`
	Search    interface{} `json:"search"`
}

func (q *Queries) CountJoinedBusinessesByProfileID(ctx context.Context, arg CountJoinedBusinessesByProfileIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countJoinedBusinessesByProfileID, arg.ProfileID, arg.Search)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getJoinedBusinessesByProfileID = `-- name: GetJoinedBusinessesByProfileID :many
SELECT
  bm.id                AS member_id,
  bm.status            AS member_status,
  bm.role              AS member_role,
  bm.answered_at       AS member_answered_at,

  br.id                AS business_root_id,
  br.created_at        AS business_root_created_at,
  br.updated_at        AS business_root_updated_at,

  bk.name              AS business_name,
  bk.description       AS business_description,
  bk.primary_logo_url  AS business_logo_url

FROM business_members bm
JOIN business_roots br
  ON br.id = bm.business_root_id
JOIN business_knowledges bk
  ON bk.business_root_id = br.id

WHERE
  bm.profile_id = $1
  AND bm.status = 'accepted'
  AND bk.deleted_at IS NULL
  AND (
    COALESCE($2, '') = ''
    OR bk.name ILIKE ('%' || $2 || '%')
  )

ORDER BY
  -- name
  CASE WHEN $3 = 'name' AND $4 = 'asc'  THEN bk.name END ASC,
  CASE WHEN $3 = 'name' AND $4 = 'desc' THEN bk.name END DESC,

  -- created_at
  CASE WHEN $3 = 'created_at' AND $4 = 'asc'  THEN br.created_at END ASC,
  CASE WHEN $3 = 'created_at' AND $4 = 'desc' THEN br.created_at END DESC,

  -- updated_at
  CASE WHEN $3 = 'updated_at' AND $4 = 'asc'  THEN br.updated_at END ASC,
  CASE WHEN $3 = 'updated_at' AND $4 = 'desc' THEN br.updated_at END DESC,

  -- fallback stable order
  br.created_at DESC,
  br.id DESC

LIMIT $6
OFFSET $5
`

type GetJoinedBusinessesByProfileIDParams struct {
	ProfileID  uuid.UUID   `json:"profile_id"`
	Search     interface{} `json:"search"`
	SortBy     interface{} `json:"sort_by"`
	SortDir    interface{} `json:"sort_dir"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

type GetJoinedBusinessesByProfileIDRow struct {
	MemberID              uuid.UUID            `json:"member_id"`
	MemberStatus          BusinessMemberStatus `json:"member_status"`
	MemberRole            BusinessMemberRole   `json:"member_role"`
	MemberAnsweredAt      sql.NullTime         `json:"member_answered_at"`
	BusinessRootID        uuid.UUID            `json:"business_root_id"`
	BusinessRootCreatedAt time.Time            `json:"business_root_created_at"`
	BusinessRootUpdatedAt time.Time            `json:"business_root_updated_at"`
	BusinessName          string               `json:"business_name"`
	BusinessDescription   sql.NullString       `json:"business_description"`
	BusinessLogoUrl       sql.NullString       `json:"business_logo_url"`
}

func (q *Queries) GetJoinedBusinessesByProfileID(ctx context.Context, arg GetJoinedBusinessesByProfileIDParams) ([]GetJoinedBusinessesByProfileIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getJoinedBusinessesByProfileID,
		arg.ProfileID,
		arg.Search,
		arg.SortBy,
		arg.SortDir,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetJoinedBusinessesByProfileIDRow
	for rows.Next() {
		var i GetJoinedBusinessesByProfileIDRow
		if err := rows.Scan(
			&i.MemberID,
			&i.MemberStatus,
			&i.MemberRole,
			&i.MemberAnsweredAt,
			&i.BusinessRootID,
			&i.BusinessRootCreatedAt,
			&i.BusinessRootUpdatedAt,
			&i.BusinessName,
			&i.BusinessDescription,
			&i.BusinessLogoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
