// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: business_role.sql

package entity

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createBusinessRole = `-- name: CreateBusinessRole :one
INSERT INTO business_roles (
    target_audience,
    tone,
    audience_persona,
    hashtags,
    call_to_action,
    goals,
    business_root_id
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, target_audience, tone, audience_persona, hashtags, call_to_action, goals, business_root_id, created_at, updated_at, deleted_at
`

type CreateBusinessRoleParams struct {
	TargetAudience  string         `json:"target_audience"`
	Tone            string         `json:"tone"`
	AudiencePersona string         `json:"audience_persona"`
	Hashtags        []string       `json:"hashtags"`
	CallToAction    string         `json:"call_to_action"`
	Goals           sql.NullString `json:"goals"`
	BusinessRootID  uuid.UUID      `json:"business_root_id"`
}

func (q *Queries) CreateBusinessRole(ctx context.Context, arg CreateBusinessRoleParams) (BusinessRole, error) {
	row := q.db.QueryRowContext(ctx, createBusinessRole,
		arg.TargetAudience,
		arg.Tone,
		arg.AudiencePersona,
		pq.Array(arg.Hashtags),
		arg.CallToAction,
		arg.Goals,
		arg.BusinessRootID,
	)
	var i BusinessRole
	err := row.Scan(
		&i.ID,
		&i.TargetAudience,
		&i.Tone,
		&i.AudiencePersona,
		pq.Array(&i.Hashtags),
		&i.CallToAction,
		&i.Goals,
		&i.BusinessRootID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteBusinessRoleByBusinessRootID = `-- name: SoftDeleteBusinessRoleByBusinessRootID :one
UPDATE business_roles
SET deleted_at = NOW()
WHERE business_root_id = $1
RETURNING id
`

func (q *Queries) SoftDeleteBusinessRoleByBusinessRootID(ctx context.Context, businessRootID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, softDeleteBusinessRoleByBusinessRootID, businessRootID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
