// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: business_setup.sql

package entity

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const setupBusinessRootFirstTime = `-- name: SetupBusinessRootFirstTime :one
WITH r AS (
  INSERT INTO business_roots DEFAULT VALUES
  RETURNING id
),
k AS (
  INSERT INTO business_knowledges (
    name, primary_logo_url, category, description,
    unique_selling_point, website_url, vision_mission, location, color_tone,
    business_root_id
  )
  SELECT
    $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    r.id
  FROM r
  RETURNING id, business_root_id
),
p AS (
  INSERT INTO business_products (
    name, category, description,
    currency, price, image_urls,
    business_root_id
  )
  SELECT
    $11, $12, $13,
    $14, $15, $16::varchar(255)[],
    r.id
  FROM r
  RETURNING id, business_root_id
),
ro AS (
  INSERT INTO business_roles (
    target_audience, tone, audience_persona, hashtags, call_to_action, goals,
    business_root_id
  )
  SELECT
    $17, $18, $19, $20::varchar(255)[], $21, $22,
    r.id
  FROM r
  RETURNING id, business_root_id
),
m AS (
  INSERT INTO business_members (
    status, role, answered_at,
    business_root_id, profile_id
  )
  SELECT
    'accepted'::business_member_status,
    'owner'::business_member_role,
    CURRENT_TIMESTAMP,
    r.id,
    $1
  FROM r
  RETURNING id, business_root_id, profile_id
)
SELECT
  r.id  AS business_root_id,
  k.id  AS business_knowledge_id,
  p.id  AS business_product_id,
  ro.id AS business_role_id,
  m.id  AS business_member_id
FROM r, k, p, ro, m
`

type SetupBusinessRootFirstTimeParams struct {
	ProfileID          uuid.UUID      `json:"profile_id"`
	Name               string         `json:"name"`
	PrimaryLogoUrl     sql.NullString `json:"primary_logo_url"`
	Category           string         `json:"category"`
	Description        sql.NullString `json:"description"`
	UniqueSellingPoint sql.NullString `json:"unique_selling_point"`
	WebsiteUrl         sql.NullString `json:"website_url"`
	VisionMission      sql.NullString `json:"vision_mission"`
	Location           sql.NullString `json:"location"`
	ColorTone          sql.NullString `json:"color_tone"`
	Name_2             string         `json:"name_2"`
	Category_2         string         `json:"category_2"`
	Description_2      sql.NullString `json:"description_2"`
	Currency           string         `json:"currency"`
	Price              string         `json:"price"`
	Column16           []string       `json:"column_16"`
	TargetAudience     string         `json:"target_audience"`
	Tone               string         `json:"tone"`
	AudiencePersona    string         `json:"audience_persona"`
	Column20           []string       `json:"column_20"`
	CallToAction       string         `json:"call_to_action"`
	Goals              sql.NullString `json:"goals"`
}

type SetupBusinessRootFirstTimeRow struct {
	BusinessRootID      uuid.UUID `json:"business_root_id"`
	BusinessKnowledgeID uuid.UUID `json:"business_knowledge_id"`
	BusinessProductID   uuid.UUID `json:"business_product_id"`
	BusinessRoleID      uuid.UUID `json:"business_role_id"`
	BusinessMemberID    uuid.UUID `json:"business_member_id"`
}

func (q *Queries) SetupBusinessRootFirstTime(ctx context.Context, arg SetupBusinessRootFirstTimeParams) (SetupBusinessRootFirstTimeRow, error) {
	row := q.db.QueryRowContext(ctx, setupBusinessRootFirstTime,
		arg.ProfileID,
		arg.Name,
		arg.PrimaryLogoUrl,
		arg.Category,
		arg.Description,
		arg.UniqueSellingPoint,
		arg.WebsiteUrl,
		arg.VisionMission,
		arg.Location,
		arg.ColorTone,
		arg.Name_2,
		arg.Category_2,
		arg.Description_2,
		arg.Currency,
		arg.Price,
		pq.Array(arg.Column16),
		arg.TargetAudience,
		arg.Tone,
		arg.AudiencePersona,
		pq.Array(arg.Column20),
		arg.CallToAction,
		arg.Goals,
	)
	var i SetupBusinessRootFirstTimeRow
	err := row.Scan(
		&i.BusinessRootID,
		&i.BusinessKnowledgeID,
		&i.BusinessProductID,
		&i.BusinessRoleID,
		&i.BusinessMemberID,
	)
	return i, err
}
