// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: business_member_status_history.sql

package entity

import (
	"context"
)

const createBusinessMemberStatusHistory = `-- name: CreateBusinessMemberStatusHistory :one
INSERT INTO business_member_status_histories (
	member_id,
	status,
	role
)
VALUES (
	$1,
	$2,
	$3
)
RETURNING id, status, role, member_id, created_at, updated_at, deleted_at
`

type CreateBusinessMemberStatusHistoryParams struct {
	MemberID int64                `json:"member_id"`
	Status   BusinessMemberStatus `json:"status"`
	Role     BusinessMemberRole   `json:"role"`
}

func (q *Queries) CreateBusinessMemberStatusHistory(ctx context.Context, arg CreateBusinessMemberStatusHistoryParams) (BusinessMemberStatusHistory, error) {
	row := q.db.QueryRowContext(ctx, createBusinessMemberStatusHistory, arg.MemberID, arg.Status, arg.Role)
	var i BusinessMemberStatusHistory
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Role,
		&i.MemberID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
