// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: business_timezone_pref.sql

package entity

import (
	"context"

	"github.com/google/uuid"
)

const getBusinessTimezonePrefByBusinessRootId = `-- name: GetBusinessTimezonePrefByBusinessRootId :one
SELECT id, business_root_id, timezone, created_at, updated_at FROM business_timezone_prefs WHERE business_root_id = $1 LIMIT 1
`

func (q *Queries) GetBusinessTimezonePrefByBusinessRootId(ctx context.Context, businessRootID uuid.UUID) (BusinessTimezonePref, error) {
	row := q.db.QueryRowContext(ctx, getBusinessTimezonePrefByBusinessRootId, businessRootID)
	var i BusinessTimezonePref
	err := row.Scan(
		&i.ID,
		&i.BusinessRootID,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBusinessTimezonePref = `-- name: UpsertBusinessTimezonePref :one
INSERT INTO business_timezone_prefs (business_root_id, timezone)
VALUES ($1, $2)
ON CONFLICT (business_root_id) DO UPDATE
SET timezone = EXCLUDED.timezone
RETURNING id, business_root_id, timezone, created_at, updated_at
`

type UpsertBusinessTimezonePrefParams struct {
	BusinessRootID uuid.UUID `json:"business_root_id"`
	Timezone       string    `json:"timezone"`
}

func (q *Queries) UpsertBusinessTimezonePref(ctx context.Context, arg UpsertBusinessTimezonePrefParams) (BusinessTimezonePref, error) {
	row := q.db.QueryRowContext(ctx, upsertBusinessTimezonePref, arg.BusinessRootID, arg.Timezone)
	var i BusinessTimezonePref
	err := row.Scan(
		&i.ID,
		&i.BusinessRootID,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
