// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: business_product.sql

package entity

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createBusinessProduct = `-- name: CreateBusinessProduct :one
INSERT INTO business_products (
    name,
    category,
    description,
    currency,
    price,
    image_urls,
    business_root_id
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, name, category, description, currency, price, image_urls, business_root_id, created_at, updated_at, deleted_at
`

type CreateBusinessProductParams struct {
	Name           string         `json:"name"`
	Category       string         `json:"category"`
	Description    sql.NullString `json:"description"`
	Currency       string         `json:"currency"`
	Price          string         `json:"price"`
	ImageUrls      []string       `json:"image_urls"`
	BusinessRootID uuid.UUID      `json:"business_root_id"`
}

func (q *Queries) CreateBusinessProduct(ctx context.Context, arg CreateBusinessProductParams) (BusinessProduct, error) {
	row := q.db.QueryRowContext(ctx, createBusinessProduct,
		arg.Name,
		arg.Category,
		arg.Description,
		arg.Currency,
		arg.Price,
		pq.Array(arg.ImageUrls),
		arg.BusinessRootID,
	)
	var i BusinessProduct
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.Currency,
		&i.Price,
		pq.Array(&i.ImageUrls),
		&i.BusinessRootID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteBusinessProductByBusinessRootID = `-- name: SoftDeleteBusinessProductByBusinessRootID :one
UPDATE business_products
SET deleted_at = NOW()
WHERE business_root_id = $1
RETURNING id
`

func (q *Queries) SoftDeleteBusinessProductByBusinessRootID(ctx context.Context, businessRootID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, softDeleteBusinessProductByBusinessRootID, businessRootID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
