// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: business_member.sql

package entity

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createBusinessMember = `-- name: CreateBusinessMember :one
INSERT INTO business_members (
	status,
	role,
	answered_at,
	business_root_id,
	profile_id
)
VALUES (
	$1,
	$2,
	$3,
	$4,
	$5
)
RETURNING id, status, role, answered_at, business_root_id, profile_id, created_at, updated_at, deleted_at
`

type CreateBusinessMemberParams struct {
	Status         BusinessMemberStatus `json:"status"`
	Role           BusinessMemberRole   `json:"role"`
	AnsweredAt     sql.NullTime         `json:"answered_at"`
	BusinessRootID int64                `json:"business_root_id"`
	ProfileID      uuid.UUID            `json:"profile_id"`
}

func (q *Queries) CreateBusinessMember(ctx context.Context, arg CreateBusinessMemberParams) (BusinessMember, error) {
	row := q.db.QueryRowContext(ctx, createBusinessMember,
		arg.Status,
		arg.Role,
		arg.AnsweredAt,
		arg.BusinessRootID,
		arg.ProfileID,
	)
	var i BusinessMember
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Role,
		&i.AnsweredAt,
		&i.BusinessRootID,
		&i.ProfileID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMemberByEmailAndBusinessRootId = `-- name: GetMemberByEmailAndBusinessRootId :one
SELECT bm.id, status, role, answered_at, business_root_id, profile_id, bm.created_at, bm.updated_at, deleted_at, p.id, name, email, image_url, country_code, phone, description, p.created_at, p.updated_at FROM business_members bm
JOIN profiles p
  ON p.id = bm.profile_id
WHERE p.email = $1
AND bm.business_root_id = $2
AND bm.deleted_at IS NULL LIMIT 1
`

type GetMemberByEmailAndBusinessRootIdParams struct {
	Email          string `json:"email"`
	BusinessRootID int64  `json:"business_root_id"`
}

type GetMemberByEmailAndBusinessRootIdRow struct {
	ID             int64                `json:"id"`
	Status         BusinessMemberStatus `json:"status"`
	Role           BusinessMemberRole   `json:"role"`
	AnsweredAt     sql.NullTime         `json:"answered_at"`
	BusinessRootID int64                `json:"business_root_id"`
	ProfileID      uuid.UUID            `json:"profile_id"`
	CreatedAt      time.Time            `json:"created_at"`
	UpdatedAt      time.Time            `json:"updated_at"`
	DeletedAt      sql.NullTime         `json:"deleted_at"`
	ID_2           uuid.UUID            `json:"id_2"`
	Name           string               `json:"name"`
	Email          string               `json:"email"`
	ImageUrl       sql.NullString       `json:"image_url"`
	CountryCode    sql.NullString       `json:"country_code"`
	Phone          sql.NullString       `json:"phone"`
	Description    sql.NullString       `json:"description"`
	CreatedAt_2    sql.NullTime         `json:"created_at_2"`
	UpdatedAt_2    sql.NullTime         `json:"updated_at_2"`
}

func (q *Queries) GetMemberByEmailAndBusinessRootId(ctx context.Context, arg GetMemberByEmailAndBusinessRootIdParams) (GetMemberByEmailAndBusinessRootIdRow, error) {
	row := q.db.QueryRowContext(ctx, getMemberByEmailAndBusinessRootId, arg.Email, arg.BusinessRootID)
	var i GetMemberByEmailAndBusinessRootIdRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Role,
		&i.AnsweredAt,
		&i.BusinessRootID,
		&i.ProfileID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ID_2,
		&i.Name,
		&i.Email,
		&i.ImageUrl,
		&i.CountryCode,
		&i.Phone,
		&i.Description,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
	)
	return i, err
}

const getMemberByProfileIdAndBusinessRootId = `-- name: GetMemberByProfileIdAndBusinessRootId :one
SELECT id, status, role, answered_at, business_root_id, profile_id, created_at, updated_at, deleted_at FROM business_members
WHERE profile_id = $1
AND business_root_id = $2
AND deleted_at IS NULL LIMIT 1
`

type GetMemberByProfileIdAndBusinessRootIdParams struct {
	ProfileID      uuid.UUID `json:"profile_id"`
	BusinessRootID int64     `json:"business_root_id"`
}

func (q *Queries) GetMemberByProfileIdAndBusinessRootId(ctx context.Context, arg GetMemberByProfileIdAndBusinessRootIdParams) (BusinessMember, error) {
	row := q.db.QueryRowContext(ctx, getMemberByProfileIdAndBusinessRootId, arg.ProfileID, arg.BusinessRootID)
	var i BusinessMember
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Role,
		&i.AnsweredAt,
		&i.BusinessRootID,
		&i.ProfileID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMembersByBusinessRootID = `-- name: GetMembersByBusinessRootID :many
SELECT
  bm.business_root_id,
  bm.id,
  bm.status,
  bm.role,
  bm.answered_at,
  bm.created_at,
  bm.updated_at,

  p.id        AS profile_id,
  p.name      AS profile_name,
  p.image_url AS profile_image_url,
  p.email     AS profile_email

FROM business_members bm
JOIN profiles p
  ON p.id = bm.profile_id

WHERE bm.business_root_id = $1

ORDER BY bm.business_root_id, bm.created_at ASC
`

type GetMembersByBusinessRootIDRow struct {
	BusinessRootID  int64                `json:"business_root_id"`
	ID              int64                `json:"id"`
	Status          BusinessMemberStatus `json:"status"`
	Role            BusinessMemberRole   `json:"role"`
	AnsweredAt      sql.NullTime         `json:"answered_at"`
	CreatedAt       time.Time            `json:"created_at"`
	UpdatedAt       time.Time            `json:"updated_at"`
	ProfileID       uuid.UUID            `json:"profile_id"`
	ProfileName     string               `json:"profile_name"`
	ProfileImageUrl sql.NullString       `json:"profile_image_url"`
	ProfileEmail    string               `json:"profile_email"`
}

func (q *Queries) GetMembersByBusinessRootID(ctx context.Context, businessRootID int64) ([]GetMembersByBusinessRootIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getMembersByBusinessRootID, businessRootID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMembersByBusinessRootIDRow
	for rows.Next() {
		var i GetMembersByBusinessRootIDRow
		if err := rows.Scan(
			&i.BusinessRootID,
			&i.ID,
			&i.Status,
			&i.Role,
			&i.AnsweredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProfileID,
			&i.ProfileName,
			&i.ProfileImageUrl,
			&i.ProfileEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMembersByBusinessRootIDWithStatus = `-- name: GetMembersByBusinessRootIDWithStatus :many
SELECT
  bm.business_root_id,
  bm.id,
  bm.status,
  bm.role,
  bm.answered_at,
  bm.created_at,
  bm.updated_at,

  p.id        AS profile_id,
  p.name      AS profile_name,
  p.image_url AS profile_image_url,
  p.email     AS profile_email,

  (bm.profile_id = $1) AS is_yourself
FROM business_members AS bm
JOIN profiles AS p
  ON p.id = bm.profile_id
WHERE
  bm.business_root_id = $2
  AND bm.deleted_at IS NULL
  AND (
    CAST($3 AS boolean) IS NULL
    OR (bm.status = 'accepted'::business_member_status) = CAST($3 AS boolean)
  )
ORDER BY bm.business_root_id, bm.created_at ASC
`

type GetMembersByBusinessRootIDWithStatusParams struct {
	ProfileID      uuid.UUID    `json:"profile_id"`
	BusinessRootID int64        `json:"business_root_id"`
	IsVerified     sql.NullBool `json:"is_verified"`
}

type GetMembersByBusinessRootIDWithStatusRow struct {
	BusinessRootID  int64                `json:"business_root_id"`
	ID              int64                `json:"id"`
	Status          BusinessMemberStatus `json:"status"`
	Role            BusinessMemberRole   `json:"role"`
	AnsweredAt      sql.NullTime         `json:"answered_at"`
	CreatedAt       time.Time            `json:"created_at"`
	UpdatedAt       time.Time            `json:"updated_at"`
	ProfileID       uuid.UUID            `json:"profile_id"`
	ProfileName     string               `json:"profile_name"`
	ProfileImageUrl sql.NullString       `json:"profile_image_url"`
	ProfileEmail    string               `json:"profile_email"`
	IsYourself      bool                 `json:"is_yourself"`
}

func (q *Queries) GetMembersByBusinessRootIDWithStatus(ctx context.Context, arg GetMembersByBusinessRootIDWithStatusParams) ([]GetMembersByBusinessRootIDWithStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, getMembersByBusinessRootIDWithStatus, arg.ProfileID, arg.BusinessRootID, arg.IsVerified)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMembersByBusinessRootIDWithStatusRow
	for rows.Next() {
		var i GetMembersByBusinessRootIDWithStatusRow
		if err := rows.Scan(
			&i.BusinessRootID,
			&i.ID,
			&i.Status,
			&i.Role,
			&i.AnsweredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProfileID,
			&i.ProfileName,
			&i.ProfileImageUrl,
			&i.ProfileEmail,
			&i.IsYourself,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMembersByBusinessRootIDs = `-- name: GetMembersByBusinessRootIDs :many
SELECT
  bm.business_root_id,
  bm.status,
  bm.role,

  p.id        AS profile_id,
  p.name      AS profile_name,
  p.image_url AS profile_image_url,
  p.email     AS profile_email

FROM business_members bm
JOIN profiles p
  ON p.id = bm.profile_id

WHERE bm.business_root_id = ANY($1::bigint[])

ORDER BY bm.business_root_id, bm.created_at ASC
`

type GetMembersByBusinessRootIDsRow struct {
	BusinessRootID  int64                `json:"business_root_id"`
	Status          BusinessMemberStatus `json:"status"`
	Role            BusinessMemberRole   `json:"role"`
	ProfileID       uuid.UUID            `json:"profile_id"`
	ProfileName     string               `json:"profile_name"`
	ProfileImageUrl sql.NullString       `json:"profile_image_url"`
	ProfileEmail    string               `json:"profile_email"`
}

func (q *Queries) GetMembersByBusinessRootIDs(ctx context.Context, businessRootIds []int64) ([]GetMembersByBusinessRootIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, getMembersByBusinessRootIDs, pq.Array(businessRootIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMembersByBusinessRootIDsRow
	for rows.Next() {
		var i GetMembersByBusinessRootIDsRow
		if err := rows.Scan(
			&i.BusinessRootID,
			&i.Status,
			&i.Role,
			&i.ProfileID,
			&i.ProfileName,
			&i.ProfileImageUrl,
			&i.ProfileEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBusinessMemberAnsweredAt = `-- name: SetBusinessMemberAnsweredAt :one
UPDATE business_members
SET answered_at = NOW()
WHERE id = $1
RETURNING id, status, role, answered_at, business_root_id, profile_id, created_at, updated_at, deleted_at
`

func (q *Queries) SetBusinessMemberAnsweredAt(ctx context.Context, id int64) (BusinessMember, error) {
	row := q.db.QueryRowContext(ctx, setBusinessMemberAnsweredAt, id)
	var i BusinessMember
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Role,
		&i.AnsweredAt,
		&i.BusinessRootID,
		&i.ProfileID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteBusinessMemberByBusinessRootID = `-- name: SoftDeleteBusinessMemberByBusinessRootID :one
UPDATE business_members
SET deleted_at = NOW()
WHERE business_root_id = $1
RETURNING id
`

func (q *Queries) SoftDeleteBusinessMemberByBusinessRootID(ctx context.Context, businessRootID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, softDeleteBusinessMemberByBusinessRootID, businessRootID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateBusinessMemberRole = `-- name: UpdateBusinessMemberRole :one
UPDATE business_members
SET role = $1
WHERE id = $2
RETURNING id, status, role, answered_at, business_root_id, profile_id, created_at, updated_at, deleted_at
`

type UpdateBusinessMemberRoleParams struct {
	Role BusinessMemberRole `json:"role"`
	ID   int64              `json:"id"`
}

func (q *Queries) UpdateBusinessMemberRole(ctx context.Context, arg UpdateBusinessMemberRoleParams) (BusinessMember, error) {
	row := q.db.QueryRowContext(ctx, updateBusinessMemberRole, arg.Role, arg.ID)
	var i BusinessMember
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Role,
		&i.AnsweredAt,
		&i.BusinessRootID,
		&i.ProfileID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateBusinessMemberStatus = `-- name: UpdateBusinessMemberStatus :one
UPDATE business_members
SET status = $1
WHERE id = $2
RETURNING id, status, role, answered_at, business_root_id, profile_id, created_at, updated_at, deleted_at
`

type UpdateBusinessMemberStatusParams struct {
	Status BusinessMemberStatus `json:"status"`
	ID     int64                `json:"id"`
}

func (q *Queries) UpdateBusinessMemberStatus(ctx context.Context, arg UpdateBusinessMemberStatusParams) (BusinessMember, error) {
	row := q.db.QueryRowContext(ctx, updateBusinessMemberStatus, arg.Status, arg.ID)
	var i BusinessMember
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Role,
		&i.AnsweredAt,
		&i.BusinessRootID,
		&i.ProfileID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateManyBusinessMemberStatus = `-- name: UpdateManyBusinessMemberStatus :exec
UPDATE business_members
SET status = $1
WHERE id = ANY($2::bigint[])
`

type UpdateManyBusinessMemberStatusParams struct {
	Status BusinessMemberStatus `json:"status"`
	Ids    []int64              `json:"ids"`
}

func (q *Queries) UpdateManyBusinessMemberStatus(ctx context.Context, arg UpdateManyBusinessMemberStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateManyBusinessMemberStatus, arg.Status, pq.Array(arg.Ids))
	return err
}
