// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: generated_image_post.sql

package entity

import (
	"context"
	"database/sql"
	"time"
)

const countGeneratedImagePostsByBusinessId = `-- name: CountGeneratedImagePostsByBusinessId :one
SELECT COUNT(*)
FROM generated_image_posts gip
WHERE gip.business_root_id = $1
  AND gip.deleted_at IS NULL
  AND ($2::generated_image_post_status IS NULL OR gip.status = $2::generated_image_post_status)
  AND ($3::generated_image_post_mode IS NULL OR gip.mode = $3::generated_image_post_mode)
  AND ($4::BIGINT IS NULL OR gip.business_product_id = $4::BIGINT)
  AND ($5::TIMESTAMPTZ IS NULL OR gip.created_at >= $5::TIMESTAMPTZ)
  AND ($6::TIMESTAMPTZ IS NULL OR gip.created_at <= $6::TIMESTAMPTZ)
`

type CountGeneratedImagePostsByBusinessIdParams struct {
	BusinessRootID    int64                        `json:"business_root_id"`
	Status            NullGeneratedImagePostStatus `json:"status"`
	Mode              NullGeneratedImagePostMode   `json:"mode"`
	BusinessProductID sql.NullInt64                `json:"business_product_id"`
	DateStart         sql.NullTime                 `json:"date_start"`
	DateEnd           sql.NullTime                 `json:"date_end"`
}

func (q *Queries) CountGeneratedImagePostsByBusinessId(ctx context.Context, arg CountGeneratedImagePostsByBusinessIdParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGeneratedImagePostsByBusinessId,
		arg.BusinessRootID,
		arg.Status,
		arg.Mode,
		arg.BusinessProductID,
		arg.DateStart,
		arg.DateEnd,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGeneratedImagePost = `-- name: CreateGeneratedImagePost :one

INSERT INTO generated_image_posts (
    status,
    business_root_id,
    business_product_id,
    app_generative_image_model_id,
    app_generative_text_model_id,
    recorded_model_name,
    recorded_model_provider,
    mode,
    num_of_images,
    ratio,
    additional_prompt,
    design_style,
    category,
    reference_image_url,
    mask_image_url,
    image_size,
    current_caption,
    adv_bk_name,
    adv_bk_category,
    adv_bk_description,
    adv_bk_location,
    adv_bk_logo,
    adv_bk_unique_selling_point,
    adv_bk_website,
    adv_bk_vision_mission,
    adv_bk_color_tone,
    adv_pd_name,
    adv_pd_category,
    adv_pd_description,
    adv_pd_price,
    adv_rl_hashtags,
    rss_title,
    rss_url,
    rss_published_at,
    rss_image_url,
    rss_summary,
    rss_publisher
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22,
    $23,
    $24,
    $25,
    $26,
    $27,
    $28,
    $29,
    $30,
    $31,
    $32,
    $33,
    $34,
    $35,
    $36,
    $37
) RETURNING id, status, error_log, generated_image_prompt, generated_caption_prompt, business_root_id, business_product_id, app_generative_image_model_id, app_generative_text_model_id, recorded_model_name, recorded_model_provider, mode, num_of_images, ratio, additional_prompt, design_style, category, reference_image_url, mask_image_url, image_size, current_caption, adv_bk_name, adv_bk_category, adv_bk_description, adv_bk_location, adv_bk_logo, adv_bk_unique_selling_point, adv_bk_website, adv_bk_vision_mission, adv_bk_color_tone, adv_pd_name, adv_pd_category, adv_pd_description, adv_pd_price, adv_rl_hashtags, rss_title, rss_url, rss_published_at, rss_image_url, rss_summary, rss_publisher, created_at, updated_at, deleted_at, attempts
`

type CreateGeneratedImagePostParams struct {
	Status                    GeneratedImagePostStatus `json:"status"`
	BusinessRootID            int64                    `json:"business_root_id"`
	BusinessProductID         int64                    `json:"business_product_id"`
	AppGenerativeImageModelID int64                    `json:"app_generative_image_model_id"`
	AppGenerativeTextModelID  sql.NullInt64            `json:"app_generative_text_model_id"`
	RecordedModelName         string                   `json:"recorded_model_name"`
	RecordedModelProvider     string                   `json:"recorded_model_provider"`
	Mode                      GeneratedImagePostMode   `json:"mode"`
	NumOfImages               int32                    `json:"num_of_images"`
	Ratio                     string                   `json:"ratio"`
	AdditionalPrompt          sql.NullString           `json:"additional_prompt"`
	DesignStyle               sql.NullString           `json:"design_style"`
	Category                  sql.NullString           `json:"category"`
	ReferenceImageUrl         sql.NullString           `json:"reference_image_url"`
	MaskImageUrl              sql.NullString           `json:"mask_image_url"`
	ImageSize                 sql.NullString           `json:"image_size"`
	CurrentCaption            sql.NullString           `json:"current_caption"`
	AdvBkName                 bool                     `json:"adv_bk_name"`
	AdvBkCategory             bool                     `json:"adv_bk_category"`
	AdvBkDescription          bool                     `json:"adv_bk_description"`
	AdvBkLocation             bool                     `json:"adv_bk_location"`
	AdvBkLogo                 bool                     `json:"adv_bk_logo"`
	AdvBkUniqueSellingPoint   bool                     `json:"adv_bk_unique_selling_point"`
	AdvBkWebsite              bool                     `json:"adv_bk_website"`
	AdvBkVisionMission        bool                     `json:"adv_bk_vision_mission"`
	AdvBkColorTone            bool                     `json:"adv_bk_color_tone"`
	AdvPdName                 bool                     `json:"adv_pd_name"`
	AdvPdCategory             bool                     `json:"adv_pd_category"`
	AdvPdDescription          bool                     `json:"adv_pd_description"`
	AdvPdPrice                bool                     `json:"adv_pd_price"`
	AdvRlHashtags             bool                     `json:"adv_rl_hashtags"`
	RssTitle                  sql.NullString           `json:"rss_title"`
	RssUrl                    sql.NullString           `json:"rss_url"`
	RssPublishedAt            sql.NullTime             `json:"rss_published_at"`
	RssImageUrl               sql.NullString           `json:"rss_image_url"`
	RssSummary                sql.NullString           `json:"rss_summary"`
	RssPublisher              sql.NullString           `json:"rss_publisher"`
}

// internal/repository/queries/generated_image_post.sql
func (q *Queries) CreateGeneratedImagePost(ctx context.Context, arg CreateGeneratedImagePostParams) (GeneratedImagePost, error) {
	row := q.db.QueryRowContext(ctx, createGeneratedImagePost,
		arg.Status,
		arg.BusinessRootID,
		arg.BusinessProductID,
		arg.AppGenerativeImageModelID,
		arg.AppGenerativeTextModelID,
		arg.RecordedModelName,
		arg.RecordedModelProvider,
		arg.Mode,
		arg.NumOfImages,
		arg.Ratio,
		arg.AdditionalPrompt,
		arg.DesignStyle,
		arg.Category,
		arg.ReferenceImageUrl,
		arg.MaskImageUrl,
		arg.ImageSize,
		arg.CurrentCaption,
		arg.AdvBkName,
		arg.AdvBkCategory,
		arg.AdvBkDescription,
		arg.AdvBkLocation,
		arg.AdvBkLogo,
		arg.AdvBkUniqueSellingPoint,
		arg.AdvBkWebsite,
		arg.AdvBkVisionMission,
		arg.AdvBkColorTone,
		arg.AdvPdName,
		arg.AdvPdCategory,
		arg.AdvPdDescription,
		arg.AdvPdPrice,
		arg.AdvRlHashtags,
		arg.RssTitle,
		arg.RssUrl,
		arg.RssPublishedAt,
		arg.RssImageUrl,
		arg.RssSummary,
		arg.RssPublisher,
	)
	var i GeneratedImagePost
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.ErrorLog,
		&i.GeneratedImagePrompt,
		&i.GeneratedCaptionPrompt,
		&i.BusinessRootID,
		&i.BusinessProductID,
		&i.AppGenerativeImageModelID,
		&i.AppGenerativeTextModelID,
		&i.RecordedModelName,
		&i.RecordedModelProvider,
		&i.Mode,
		&i.NumOfImages,
		&i.Ratio,
		&i.AdditionalPrompt,
		&i.DesignStyle,
		&i.Category,
		&i.ReferenceImageUrl,
		&i.MaskImageUrl,
		&i.ImageSize,
		&i.CurrentCaption,
		&i.AdvBkName,
		&i.AdvBkCategory,
		&i.AdvBkDescription,
		&i.AdvBkLocation,
		&i.AdvBkLogo,
		&i.AdvBkUniqueSellingPoint,
		&i.AdvBkWebsite,
		&i.AdvBkVisionMission,
		&i.AdvBkColorTone,
		&i.AdvPdName,
		&i.AdvPdCategory,
		&i.AdvPdDescription,
		&i.AdvPdPrice,
		&i.AdvRlHashtags,
		&i.RssTitle,
		&i.RssUrl,
		&i.RssPublishedAt,
		&i.RssImageUrl,
		&i.RssSummary,
		&i.RssPublisher,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Attempts,
	)
	return i, err
}

const getAllGeneratedImagePostsByBusinessId = `-- name: GetAllGeneratedImagePostsByBusinessId :many
SELECT
    gip.id, gip.status, gip.error_log, gip.generated_image_prompt, gip.generated_caption_prompt, gip.business_root_id, gip.business_product_id, gip.app_generative_image_model_id, gip.app_generative_text_model_id, gip.recorded_model_name, gip.recorded_model_provider, gip.mode, gip.num_of_images, gip.ratio, gip.additional_prompt, gip.design_style, gip.category, gip.reference_image_url, gip.mask_image_url, gip.image_size, gip.current_caption, gip.adv_bk_name, gip.adv_bk_category, gip.adv_bk_description, gip.adv_bk_location, gip.adv_bk_logo, gip.adv_bk_unique_selling_point, gip.adv_bk_website, gip.adv_bk_vision_mission, gip.adv_bk_color_tone, gip.adv_pd_name, gip.adv_pd_category, gip.adv_pd_description, gip.adv_pd_price, gip.adv_rl_hashtags, gip.rss_title, gip.rss_url, gip.rss_published_at, gip.rss_image_url, gip.rss_summary, gip.rss_publisher, gip.created_at, gip.updated_at, gip.deleted_at, gip.attempts,
    -- items as JSON array
    COALESCE(
        (SELECT json_agg(json_build_object(
            'id', i.id,
            'image_url', i.image_url,
            'token_used', i.token_used,
            'created_at', i.created_at
        ) ORDER BY i.id)
         FROM generated_image_post_items i
         WHERE i.generated_image_post_id = gip.id AND i.deleted_at IS NULL),
        '[]'::json
    ) AS items,
    -- caption (COALESCE to handle NULL when no caption exists)
    COALESCE(
        (SELECT json_build_object(
            'id', c.id,
            'caption_text', c.caption_text,
            'token_used', c.token_used,
            'created_at', c.created_at
        )
         FROM generated_image_post_captions c
         WHERE c.generated_image_post_id = gip.id AND c.deleted_at IS NULL
         LIMIT 1),
        '{}'::json
    ) AS caption
FROM generated_image_posts gip
WHERE gip.business_root_id = $1
  AND gip.deleted_at IS NULL
  -- filter by status
  AND ($2::generated_image_post_status IS NULL OR gip.status = $2::generated_image_post_status)
  -- filter by mode
  AND ($3::generated_image_post_mode IS NULL OR gip.mode = $3::generated_image_post_mode)
  -- filter by product
  AND ($4::BIGINT IS NULL OR gip.business_product_id = $4::BIGINT)
  -- filter by date range
  AND ($5::TIMESTAMPTZ IS NULL OR gip.created_at >= $5::TIMESTAMPTZ)
  AND ($6::TIMESTAMPTZ IS NULL OR gip.created_at <= $6::TIMESTAMPTZ)
ORDER BY
    CASE WHEN $7::TEXT = 'id' AND $8::TEXT = 'asc' THEN gip.id END ASC,
    CASE WHEN $7::TEXT = 'id' AND $8::TEXT = 'desc' THEN gip.id END DESC,
    CASE WHEN $7::TEXT = 'created_at' AND $8::TEXT = 'asc' THEN gip.created_at END ASC,
    CASE WHEN $7::TEXT = 'created_at' AND $8::TEXT = 'desc' THEN gip.created_at END DESC,
    CASE WHEN $7::TEXT = 'updated_at' AND $8::TEXT = 'asc' THEN gip.updated_at END ASC,
    CASE WHEN $7::TEXT = 'updated_at' AND $8::TEXT = 'desc' THEN gip.updated_at END DESC,
    gip.id DESC -- default sort
LIMIT $10 OFFSET $9
`

type GetAllGeneratedImagePostsByBusinessIdParams struct {
	BusinessRootID    int64                        `json:"business_root_id"`
	Status            NullGeneratedImagePostStatus `json:"status"`
	Mode              NullGeneratedImagePostMode   `json:"mode"`
	BusinessProductID sql.NullInt64                `json:"business_product_id"`
	DateStart         sql.NullTime                 `json:"date_start"`
	DateEnd           sql.NullTime                 `json:"date_end"`
	SortBy            sql.NullString               `json:"sort_by"`
	SortDir           sql.NullString               `json:"sort_dir"`
	PageOffset        int32                        `json:"page_offset"`
	PageLimit         int32                        `json:"page_limit"`
}

type GetAllGeneratedImagePostsByBusinessIdRow struct {
	ID                        int64                    `json:"id"`
	Status                    GeneratedImagePostStatus `json:"status"`
	ErrorLog                  sql.NullString           `json:"error_log"`
	GeneratedImagePrompt      sql.NullString           `json:"generated_image_prompt"`
	GeneratedCaptionPrompt    sql.NullString           `json:"generated_caption_prompt"`
	BusinessRootID            int64                    `json:"business_root_id"`
	BusinessProductID         int64                    `json:"business_product_id"`
	AppGenerativeImageModelID int64                    `json:"app_generative_image_model_id"`
	AppGenerativeTextModelID  sql.NullInt64            `json:"app_generative_text_model_id"`
	RecordedModelName         string                   `json:"recorded_model_name"`
	RecordedModelProvider     string                   `json:"recorded_model_provider"`
	Mode                      GeneratedImagePostMode   `json:"mode"`
	NumOfImages               int32                    `json:"num_of_images"`
	Ratio                     string                   `json:"ratio"`
	AdditionalPrompt          sql.NullString           `json:"additional_prompt"`
	DesignStyle               sql.NullString           `json:"design_style"`
	Category                  sql.NullString           `json:"category"`
	ReferenceImageUrl         sql.NullString           `json:"reference_image_url"`
	MaskImageUrl              sql.NullString           `json:"mask_image_url"`
	ImageSize                 sql.NullString           `json:"image_size"`
	CurrentCaption            sql.NullString           `json:"current_caption"`
	AdvBkName                 bool                     `json:"adv_bk_name"`
	AdvBkCategory             bool                     `json:"adv_bk_category"`
	AdvBkDescription          bool                     `json:"adv_bk_description"`
	AdvBkLocation             bool                     `json:"adv_bk_location"`
	AdvBkLogo                 bool                     `json:"adv_bk_logo"`
	AdvBkUniqueSellingPoint   bool                     `json:"adv_bk_unique_selling_point"`
	AdvBkWebsite              bool                     `json:"adv_bk_website"`
	AdvBkVisionMission        bool                     `json:"adv_bk_vision_mission"`
	AdvBkColorTone            bool                     `json:"adv_bk_color_tone"`
	AdvPdName                 bool                     `json:"adv_pd_name"`
	AdvPdCategory             bool                     `json:"adv_pd_category"`
	AdvPdDescription          bool                     `json:"adv_pd_description"`
	AdvPdPrice                bool                     `json:"adv_pd_price"`
	AdvRlHashtags             bool                     `json:"adv_rl_hashtags"`
	RssTitle                  sql.NullString           `json:"rss_title"`
	RssUrl                    sql.NullString           `json:"rss_url"`
	RssPublishedAt            sql.NullTime             `json:"rss_published_at"`
	RssImageUrl               sql.NullString           `json:"rss_image_url"`
	RssSummary                sql.NullString           `json:"rss_summary"`
	RssPublisher              sql.NullString           `json:"rss_publisher"`
	CreatedAt                 time.Time                `json:"created_at"`
	UpdatedAt                 time.Time                `json:"updated_at"`
	DeletedAt                 sql.NullTime             `json:"deleted_at"`
	Attempts                  int32                    `json:"attempts"`
	Items                     interface{}              `json:"items"`
	Caption                   interface{}              `json:"caption"`
}

func (q *Queries) GetAllGeneratedImagePostsByBusinessId(ctx context.Context, arg GetAllGeneratedImagePostsByBusinessIdParams) ([]GetAllGeneratedImagePostsByBusinessIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllGeneratedImagePostsByBusinessId,
		arg.BusinessRootID,
		arg.Status,
		arg.Mode,
		arg.BusinessProductID,
		arg.DateStart,
		arg.DateEnd,
		arg.SortBy,
		arg.SortDir,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllGeneratedImagePostsByBusinessIdRow
	for rows.Next() {
		var i GetAllGeneratedImagePostsByBusinessIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.ErrorLog,
			&i.GeneratedImagePrompt,
			&i.GeneratedCaptionPrompt,
			&i.BusinessRootID,
			&i.BusinessProductID,
			&i.AppGenerativeImageModelID,
			&i.AppGenerativeTextModelID,
			&i.RecordedModelName,
			&i.RecordedModelProvider,
			&i.Mode,
			&i.NumOfImages,
			&i.Ratio,
			&i.AdditionalPrompt,
			&i.DesignStyle,
			&i.Category,
			&i.ReferenceImageUrl,
			&i.MaskImageUrl,
			&i.ImageSize,
			&i.CurrentCaption,
			&i.AdvBkName,
			&i.AdvBkCategory,
			&i.AdvBkDescription,
			&i.AdvBkLocation,
			&i.AdvBkLogo,
			&i.AdvBkUniqueSellingPoint,
			&i.AdvBkWebsite,
			&i.AdvBkVisionMission,
			&i.AdvBkColorTone,
			&i.AdvPdName,
			&i.AdvPdCategory,
			&i.AdvPdDescription,
			&i.AdvPdPrice,
			&i.AdvRlHashtags,
			&i.RssTitle,
			&i.RssUrl,
			&i.RssPublishedAt,
			&i.RssImageUrl,
			&i.RssSummary,
			&i.RssPublisher,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Attempts,
			&i.Items,
			&i.Caption,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGeneratedImagePostById = `-- name: GetGeneratedImagePostById :one
SELECT id, status, error_log, generated_image_prompt, generated_caption_prompt, business_root_id, business_product_id, app_generative_image_model_id, app_generative_text_model_id, recorded_model_name, recorded_model_provider, mode, num_of_images, ratio, additional_prompt, design_style, category, reference_image_url, mask_image_url, image_size, current_caption, adv_bk_name, adv_bk_category, adv_bk_description, adv_bk_location, adv_bk_logo, adv_bk_unique_selling_point, adv_bk_website, adv_bk_vision_mission, adv_bk_color_tone, adv_pd_name, adv_pd_category, adv_pd_description, adv_pd_price, adv_rl_hashtags, rss_title, rss_url, rss_published_at, rss_image_url, rss_summary, rss_publisher, created_at, updated_at, deleted_at, attempts FROM generated_image_posts
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetGeneratedImagePostById(ctx context.Context, id int64) (GeneratedImagePost, error) {
	row := q.db.QueryRowContext(ctx, getGeneratedImagePostById, id)
	var i GeneratedImagePost
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.ErrorLog,
		&i.GeneratedImagePrompt,
		&i.GeneratedCaptionPrompt,
		&i.BusinessRootID,
		&i.BusinessProductID,
		&i.AppGenerativeImageModelID,
		&i.AppGenerativeTextModelID,
		&i.RecordedModelName,
		&i.RecordedModelProvider,
		&i.Mode,
		&i.NumOfImages,
		&i.Ratio,
		&i.AdditionalPrompt,
		&i.DesignStyle,
		&i.Category,
		&i.ReferenceImageUrl,
		&i.MaskImageUrl,
		&i.ImageSize,
		&i.CurrentCaption,
		&i.AdvBkName,
		&i.AdvBkCategory,
		&i.AdvBkDescription,
		&i.AdvBkLocation,
		&i.AdvBkLogo,
		&i.AdvBkUniqueSellingPoint,
		&i.AdvBkWebsite,
		&i.AdvBkVisionMission,
		&i.AdvBkColorTone,
		&i.AdvPdName,
		&i.AdvPdCategory,
		&i.AdvPdDescription,
		&i.AdvPdPrice,
		&i.AdvRlHashtags,
		&i.RssTitle,
		&i.RssUrl,
		&i.RssPublishedAt,
		&i.RssImageUrl,
		&i.RssSummary,
		&i.RssPublisher,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Attempts,
	)
	return i, err
}

const updateGeneratedImagePostError = `-- name: UpdateGeneratedImagePostError :exec
UPDATE generated_image_posts
SET 
    status = 'failed',
    error_log = $1
WHERE id = $2
`

type UpdateGeneratedImagePostErrorParams struct {
	ErrorLog sql.NullString `json:"error_log"`
	ID       int64          `json:"id"`
}

func (q *Queries) UpdateGeneratedImagePostError(ctx context.Context, arg UpdateGeneratedImagePostErrorParams) error {
	_, err := q.db.ExecContext(ctx, updateGeneratedImagePostError, arg.ErrorLog, arg.ID)
	return err
}

const updateGeneratedImagePostPrompts = `-- name: UpdateGeneratedImagePostPrompts :exec
UPDATE generated_image_posts
SET 
    generated_image_prompt = $1,
    generated_caption_prompt = $2
WHERE id = $3
`

type UpdateGeneratedImagePostPromptsParams struct {
	GeneratedImagePrompt   sql.NullString `json:"generated_image_prompt"`
	GeneratedCaptionPrompt sql.NullString `json:"generated_caption_prompt"`
	ID                     int64          `json:"id"`
}

func (q *Queries) UpdateGeneratedImagePostPrompts(ctx context.Context, arg UpdateGeneratedImagePostPromptsParams) error {
	_, err := q.db.ExecContext(ctx, updateGeneratedImagePostPrompts, arg.GeneratedImagePrompt, arg.GeneratedCaptionPrompt, arg.ID)
	return err
}

const updateGeneratedImagePostStatus = `-- name: UpdateGeneratedImagePostStatus :exec
UPDATE generated_image_posts
SET status = $1
WHERE id = $2
`

type UpdateGeneratedImagePostStatusParams struct {
	Status GeneratedImagePostStatus `json:"status"`
	ID     int64                    `json:"id"`
}

func (q *Queries) UpdateGeneratedImagePostStatus(ctx context.Context, arg UpdateGeneratedImagePostStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateGeneratedImagePostStatus, arg.Status, arg.ID)
	return err
}
