// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: generated_image_post_caption.sql

package entity

import (
	"context"
)

const createGeneratedImagePostCaption = `-- name: CreateGeneratedImagePostCaption :one

INSERT INTO generated_image_post_captions (
    generated_image_post_id,
    caption_text,
    token_used
) VALUES (
    $1,
    $2,
    $3
) RETURNING id, generated_image_post_id, caption_text, token_used, created_at, updated_at, deleted_at
`

type CreateGeneratedImagePostCaptionParams struct {
	GeneratedImagePostID int64  `json:"generated_image_post_id"`
	CaptionText          string `json:"caption_text"`
	TokenUsed            int32  `json:"token_used"`
}

// internal/repository/queries/generated_image_post_caption.sql
func (q *Queries) CreateGeneratedImagePostCaption(ctx context.Context, arg CreateGeneratedImagePostCaptionParams) (GeneratedImagePostCaption, error) {
	row := q.db.QueryRowContext(ctx, createGeneratedImagePostCaption, arg.GeneratedImagePostID, arg.CaptionText, arg.TokenUsed)
	var i GeneratedImagePostCaption
	err := row.Scan(
		&i.ID,
		&i.GeneratedImagePostID,
		&i.CaptionText,
		&i.TokenUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGeneratedImagePostCaptionByPostId = `-- name: GetGeneratedImagePostCaptionByPostId :one
SELECT id, generated_image_post_id, caption_text, token_used, created_at, updated_at, deleted_at FROM generated_image_post_captions
WHERE generated_image_post_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetGeneratedImagePostCaptionByPostId(ctx context.Context, generatedImagePostID int64) (GeneratedImagePostCaption, error) {
	row := q.db.QueryRowContext(ctx, getGeneratedImagePostCaptionByPostId, generatedImagePostID)
	var i GeneratedImagePostCaption
	err := row.Scan(
		&i.ID,
		&i.GeneratedImagePostID,
		&i.CaptionText,
		&i.TokenUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
