// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: generated_image_post_item.sql

package entity

import (
	"context"
)

const createGeneratedImagePostItem = `-- name: CreateGeneratedImagePostItem :one

INSERT INTO generated_image_post_items (
    generated_image_post_id,
    image_url,
    token_used
) VALUES (
    $1,
    $2,
    $3
) RETURNING id, generated_image_post_id, image_url, token_used, created_at, updated_at, deleted_at
`

type CreateGeneratedImagePostItemParams struct {
	GeneratedImagePostID int64  `json:"generated_image_post_id"`
	ImageUrl             string `json:"image_url"`
	TokenUsed            int32  `json:"token_used"`
}

// internal/repository/queries/generated_image_post_item.sql
func (q *Queries) CreateGeneratedImagePostItem(ctx context.Context, arg CreateGeneratedImagePostItemParams) (GeneratedImagePostItem, error) {
	row := q.db.QueryRowContext(ctx, createGeneratedImagePostItem, arg.GeneratedImagePostID, arg.ImageUrl, arg.TokenUsed)
	var i GeneratedImagePostItem
	err := row.Scan(
		&i.ID,
		&i.GeneratedImagePostID,
		&i.ImageUrl,
		&i.TokenUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGeneratedImagePostItemsByPostId = `-- name: GetGeneratedImagePostItemsByPostId :many
SELECT id, generated_image_post_id, image_url, token_used, created_at, updated_at, deleted_at FROM generated_image_post_items
WHERE generated_image_post_id = $1
  AND deleted_at IS NULL
ORDER BY id ASC
`

func (q *Queries) GetGeneratedImagePostItemsByPostId(ctx context.Context, generatedImagePostID int64) ([]GeneratedImagePostItem, error) {
	rows, err := q.db.QueryContext(ctx, getGeneratedImagePostItemsByPostId, generatedImagePostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GeneratedImagePostItem
	for rows.Next() {
		var i GeneratedImagePostItem
		if err := rows.Scan(
			&i.ID,
			&i.GeneratedImagePostID,
			&i.ImageUrl,
			&i.TokenUsed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
