// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package entity

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type AppRole string

const (
	AppRoleAdmin AppRole = "admin"
	AppRoleUser  AppRole = "user"
)

func (e *AppRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppRole(s)
	case string:
		*e = AppRole(s)
	default:
		return fmt.Errorf("unsupported scan type for AppRole: %T", src)
	}
	return nil
}

type NullAppRole struct {
	AppRole AppRole `json:"app_role"`
	Valid   bool    `json:"valid"` // Valid is true if AppRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppRole) Scan(value interface{}) error {
	if value == nil {
		ns.AppRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppRole), nil
}

type AuthProvider string

const (
	AuthProviderGoogle     AuthProvider = "google"
	AuthProviderCredential AuthProvider = "credential"
)

func (e *AuthProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthProvider(s)
	case string:
		*e = AuthProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthProvider: %T", src)
	}
	return nil
}

type NullAuthProvider struct {
	AuthProvider AuthProvider `json:"auth_provider"`
	Valid        bool         `json:"valid"` // Valid is true if AuthProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthProvider) Scan(value interface{}) error {
	if value == nil {
		ns.AuthProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthProvider), nil
}

type BusinessImageContentType string

const (
	BusinessImageContentTypePersonal  BusinessImageContentType = "personal"
	BusinessImageContentTypeGenerated BusinessImageContentType = "generated"
)

func (e *BusinessImageContentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BusinessImageContentType(s)
	case string:
		*e = BusinessImageContentType(s)
	default:
		return fmt.Errorf("unsupported scan type for BusinessImageContentType: %T", src)
	}
	return nil
}

type NullBusinessImageContentType struct {
	BusinessImageContentType BusinessImageContentType `json:"business_image_content_type"`
	Valid                    bool                     `json:"valid"` // Valid is true if BusinessImageContentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBusinessImageContentType) Scan(value interface{}) error {
	if value == nil {
		ns.BusinessImageContentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BusinessImageContentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBusinessImageContentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BusinessImageContentType), nil
}

type BusinessMemberRole string

const (
	BusinessMemberRoleOwner  BusinessMemberRole = "owner"
	BusinessMemberRoleAdmin  BusinessMemberRole = "admin"
	BusinessMemberRoleMember BusinessMemberRole = "member"
)

func (e *BusinessMemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BusinessMemberRole(s)
	case string:
		*e = BusinessMemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for BusinessMemberRole: %T", src)
	}
	return nil
}

type NullBusinessMemberRole struct {
	BusinessMemberRole BusinessMemberRole `json:"business_member_role"`
	Valid              bool               `json:"valid"` // Valid is true if BusinessMemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBusinessMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.BusinessMemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BusinessMemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBusinessMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BusinessMemberRole), nil
}

type BusinessMemberStatus string

const (
	BusinessMemberStatusPending  BusinessMemberStatus = "pending"
	BusinessMemberStatusAccepted BusinessMemberStatus = "accepted"
	BusinessMemberStatusRejected BusinessMemberStatus = "rejected"
	BusinessMemberStatusLeft     BusinessMemberStatus = "left"
	BusinessMemberStatusKicked   BusinessMemberStatus = "kicked"
	BusinessMemberStatusExpired  BusinessMemberStatus = "expired"
)

func (e *BusinessMemberStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BusinessMemberStatus(s)
	case string:
		*e = BusinessMemberStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BusinessMemberStatus: %T", src)
	}
	return nil
}

type NullBusinessMemberStatus struct {
	BusinessMemberStatus BusinessMemberStatus `json:"business_member_status"`
	Valid                bool                 `json:"valid"` // Valid is true if BusinessMemberStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBusinessMemberStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BusinessMemberStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BusinessMemberStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBusinessMemberStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BusinessMemberStatus), nil
}

type DiscountType string

const (
	DiscountTypeFixed      DiscountType = "fixed"
	DiscountTypePercentage DiscountType = "percentage"
)

func (e *DiscountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DiscountType(s)
	case string:
		*e = DiscountType(s)
	default:
		return fmt.Errorf("unsupported scan type for DiscountType: %T", src)
	}
	return nil
}

type NullDiscountType struct {
	DiscountType DiscountType `json:"discount_type"`
	Valid        bool         `json:"valid"` // Valid is true if DiscountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDiscountType) Scan(value interface{}) error {
	if value == nil {
		ns.DiscountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DiscountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDiscountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DiscountType), nil
}

type ImageProvider string

const (
	ImageProviderCloudinary ImageProvider = "cloudinary"
	ImageProviderS3         ImageProvider = "s3"
)

func (e *ImageProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ImageProvider(s)
	case string:
		*e = ImageProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for ImageProvider: %T", src)
	}
	return nil
}

type NullImageProvider struct {
	ImageProvider ImageProvider `json:"image_provider"`
	Valid         bool          `json:"valid"` // Valid is true if ImageProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullImageProvider) Scan(value interface{}) error {
	if value == nil {
		ns.ImageProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ImageProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullImageProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ImageProvider), nil
}

type ReferralType string

const (
	ReferralTypeBasic   ReferralType = "basic"
	ReferralTypeSpecial ReferralType = "special"
)

func (e *ReferralType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReferralType(s)
	case string:
		*e = ReferralType(s)
	default:
		return fmt.Errorf("unsupported scan type for ReferralType: %T", src)
	}
	return nil
}

type NullReferralType struct {
	ReferralType ReferralType `json:"referral_type"`
	Valid        bool         `json:"valid"` // Valid is true if ReferralType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReferralType) Scan(value interface{}) error {
	if value == nil {
		ns.ReferralType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReferralType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReferralType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReferralType), nil
}

type TokenType string

const (
	TokenTypeImageToken      TokenType = "image_token"
	TokenTypeVideoToken      TokenType = "video_token"
	TokenTypeLivestreamToken TokenType = "livestream_token"
)

func (e *TokenType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TokenType(s)
	case string:
		*e = TokenType(s)
	default:
		return fmt.Errorf("unsupported scan type for TokenType: %T", src)
	}
	return nil
}

type NullTokenType struct {
	TokenType TokenType `json:"token_type"`
	Valid     bool      `json:"valid"` // Valid is true if TokenType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTokenType) Scan(value interface{}) error {
	if value == nil {
		ns.TokenType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TokenType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTokenType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TokenType), nil
}

type AppCreatorImageProductCategory struct {
	ID             int64        `json:"id"`
	IndonesianName string       `json:"indonesian_name"`
	EnglishName    string       `json:"english_name"`
	CreatedAt      sql.NullTime `json:"created_at"`
	UpdatedAt      sql.NullTime `json:"updated_at"`
}

type AppCreatorImageTypeCategory struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type AppProfileReferralChange struct {
	ID                int64         `json:"id"`
	ProfileID         uuid.UUID     `json:"profile_id"`
	TotalDiscount     int64         `json:"total_discount"`
	DiscountType      DiscountType  `json:"discount_type"`
	ExpiredDays       sql.NullInt32 `json:"expired_days"`
	MaxDiscount       int64         `json:"max_discount"`
	MaxUsage          sql.NullInt32 `json:"max_usage"`
	RewardPerReferral int64         `json:"reward_per_referral"`
	CreatedAt         time.Time     `json:"created_at"`
	UpdatedAt         time.Time     `json:"updated_at"`
}

type AppProfileReferralRule struct {
	ID                int16         `json:"id"`
	TotalDiscount     int64         `json:"total_discount"`
	DiscountType      DiscountType  `json:"discount_type"`
	ExpiredDays       sql.NullInt32 `json:"expired_days"`
	MaxDiscount       int64         `json:"max_discount"`
	MaxUsage          sql.NullInt32 `json:"max_usage"`
	RewardPerReferral int64         `json:"reward_per_referral"`
	CreatedAt         time.Time     `json:"created_at"`
	UpdatedAt         time.Time     `json:"updated_at"`
}

type AppRssCategory struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

type AppRssFeed struct {
	ID               int64        `json:"id"`
	Title            string       `json:"title"`
	Url              string       `json:"url"`
	Publisher        string       `json:"publisher"`
	AppRssCategoryID int64        `json:"app_rss_category_id"`
	DeletedAt        sql.NullTime `json:"deleted_at"`
	CreatedAt        time.Time    `json:"created_at"`
	UpdatedAt        time.Time    `json:"updated_at"`
}

type AppTokenProduct struct {
	ID           uuid.UUID    `json:"id"`
	TokenType    TokenType    `json:"token_type"`
	CurrencyCode string       `json:"currency_code"`
	PriceAmount  int64        `json:"price_amount"`
	TokenAmount  int64        `json:"token_amount"`
	IsActive     bool         `json:"is_active"`
	SortOrder    int32        `json:"sort_order"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
}

type AppTokenProductChange struct {
	ID           int64     `json:"id"`
	ProfileID    uuid.UUID `json:"profile_id"`
	TokenType    TokenType `json:"token_type"`
	CurrencyCode string    `json:"currency_code"`
	PriceAmount  int64     `json:"price_amount"`
	TokenAmount  int64     `json:"token_amount"`
	IsActive     bool      `json:"is_active"`
	SortOrder    int32     `json:"sort_order"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type BusinessImageContent struct {
	ID                int64                    `json:"id"`
	ImageUrls         []string                 `json:"image_urls"`
	Caption           sql.NullString           `json:"caption"`
	Type              BusinessImageContentType `json:"type"`
	ReadyToPost       bool                     `json:"ready_to_post"`
	Category          string                   `json:"category"`
	BusinessProductID sql.NullInt64            `json:"business_product_id"`
	BusinessRootID    int64                    `json:"business_root_id"`
	CreatedAt         sql.NullTime             `json:"created_at"`
	UpdatedAt         sql.NullTime             `json:"updated_at"`
	DeletedAt         sql.NullTime             `json:"deleted_at"`
}

type BusinessKnowledge struct {
	ID                 int64          `json:"id"`
	Name               string         `json:"name"`
	PrimaryLogoUrl     sql.NullString `json:"primary_logo_url"`
	Category           string         `json:"category"`
	Description        sql.NullString `json:"description"`
	UniqueSellingPoint sql.NullString `json:"unique_selling_point"`
	WebsiteUrl         sql.NullString `json:"website_url"`
	VisionMission      sql.NullString `json:"vision_mission"`
	Location           sql.NullString `json:"location"`
	ColorTone          sql.NullString `json:"color_tone"`
	BusinessRootID     int64          `json:"business_root_id"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
	DeletedAt          sql.NullTime   `json:"deleted_at"`
}

type BusinessMember struct {
	ID             int64                `json:"id"`
	Status         BusinessMemberStatus `json:"status"`
	Role           BusinessMemberRole   `json:"role"`
	AnsweredAt     sql.NullTime         `json:"answered_at"`
	BusinessRootID int64                `json:"business_root_id"`
	ProfileID      uuid.UUID            `json:"profile_id"`
	CreatedAt      time.Time            `json:"created_at"`
	UpdatedAt      time.Time            `json:"updated_at"`
	DeletedAt      sql.NullTime         `json:"deleted_at"`
}

type BusinessMemberStatusHistory struct {
	ID        int64                `json:"id"`
	Status    BusinessMemberStatus `json:"status"`
	Role      BusinessMemberRole   `json:"role"`
	MemberID  int64                `json:"member_id"`
	CreatedAt time.Time            `json:"created_at"`
	UpdatedAt time.Time            `json:"updated_at"`
	DeletedAt sql.NullTime         `json:"deleted_at"`
}

type BusinessProduct struct {
	ID             int64          `json:"id"`
	Name           string         `json:"name"`
	Category       string         `json:"category"`
	Description    sql.NullString `json:"description"`
	Currency       string         `json:"currency"`
	Price          int64          `json:"price"`
	ImageUrls      []string       `json:"image_urls"`
	BusinessRootID int64          `json:"business_root_id"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
}

type BusinessRole struct {
	ID              int64          `json:"id"`
	TargetAudience  string         `json:"target_audience"`
	Tone            string         `json:"tone"`
	AudiencePersona string         `json:"audience_persona"`
	Hashtags        []string       `json:"hashtags"`
	CallToAction    string         `json:"call_to_action"`
	Goals           sql.NullString `json:"goals"`
	BusinessRootID  int64          `json:"business_root_id"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
}

type BusinessRoot struct {
	ID        int64        `json:"id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type BusinessRssSubscription struct {
	ID             int64        `json:"id"`
	Title          string       `json:"title"`
	IsActive       bool         `json:"is_active"`
	BusinessRootID int64        `json:"business_root_id"`
	CreatedAt      time.Time    `json:"created_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
	DeletedAt      sql.NullTime `json:"deleted_at"`
	AppRssFeedID   int64        `json:"app_rss_feed_id"`
}

type BusinessTimezonePref struct {
	ID             int32        `json:"id"`
	BusinessRootID int64        `json:"business_root_id"`
	Timezone       string       `json:"timezone"`
	CreatedAt      sql.NullTime `json:"created_at"`
	UpdatedAt      sql.NullTime `json:"updated_at"`
}

type CreatorImage struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	ImageUrl     string         `json:"image_url"`
	IsPublished  bool           `json:"is_published"`
	IsBanned     bool           `json:"is_banned"`
	BannedReason sql.NullString `json:"banned_reason"`
	Price        int64          `json:"price"`
	ProfileID    uuid.NullUUID  `json:"profile_id"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
}

type CreatorImageProductCategory struct {
	CreatorImageID    int64        `json:"creator_image_id"`
	ProductCategoryID int64        `json:"product_category_id"`
	CreatedAt         sql.NullTime `json:"created_at"`
}

type CreatorImageTypeCategory struct {
	CreatorImageID int64        `json:"creator_image_id"`
	TypeCategoryID int64        `json:"type_category_id"`
	CreatedAt      sql.NullTime `json:"created_at"`
}

type Profile struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Email       string         `json:"email"`
	ImageUrl    sql.NullString `json:"image_url"`
	CountryCode sql.NullString `json:"country_code"`
	Phone       sql.NullString `json:"phone"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	Role        AppRole        `json:"role"`
}

type ProfileReferralCode struct {
	ID                int64         `json:"id"`
	ProfileID         uuid.UUID     `json:"profile_id"`
	Code              string        `json:"code"`
	Type              ReferralType  `json:"type"`
	IsActive          bool          `json:"is_active"`
	TotalDiscount     int64         `json:"total_discount"`
	DiscountType      DiscountType  `json:"discount_type"`
	ExpiredDays       sql.NullInt32 `json:"expired_days"`
	MaxDiscount       int64         `json:"max_discount"`
	MaxUsage          sql.NullInt32 `json:"max_usage"`
	RewardPerReferral int64         `json:"reward_per_referral"`
	CreatedAt         time.Time     `json:"created_at"`
	UpdatedAt         time.Time     `json:"updated_at"`
	DeletedAt         sql.NullTime  `json:"deleted_at"`
}

type UploadedImage struct {
	ID        int64         `json:"id"`
	Hashkey   string        `json:"hashkey"`
	PublicID  string        `json:"public_id"`
	Size      int64         `json:"size"`
	ImageUrl  string        `json:"image_url"`
	Provider  ImageProvider `json:"provider"`
	Format    string        `json:"format"`
	CreatedAt sql.NullTime  `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
}

type User struct {
	ID         uuid.UUID      `json:"id"`
	Password   sql.NullString `json:"password"`
	Provider   AuthProvider   `json:"provider"`
	VerifiedAt sql.NullTime   `json:"verified_at"`
	ProfileID  uuid.UUID      `json:"profile_id"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
}
