// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment_history_action.sql

package entity

import (
	"context"

	"github.com/google/uuid"
)

const createPaymentHistoryAction = `-- name: CreatePaymentHistoryAction :one
INSERT INTO payment_history_actions (
    payment_history_id,
    name,
    label,
    value,
    value_type,
    payment_type,
    action_method,
    is_public
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, payment_history_id, name, label, value, value_type, payment_type, action_method, is_public, created_at, updated_at
`

type CreatePaymentHistoryActionParams struct {
	PaymentHistoryID uuid.UUID              `json:"payment_history_id"`
	Name             string                 `json:"name"`
	Label            string                 `json:"label"`
	Value            string                 `json:"value"`
	ValueType        PaymentActionValueType `json:"value_type"`
	PaymentType      AppPaymentMethodType   `json:"payment_type"`
	ActionMethod     string                 `json:"action_method"`
	IsPublic         bool                   `json:"is_public"`
}

func (q *Queries) CreatePaymentHistoryAction(ctx context.Context, arg CreatePaymentHistoryActionParams) (PaymentHistoryAction, error) {
	row := q.db.QueryRowContext(ctx, createPaymentHistoryAction,
		arg.PaymentHistoryID,
		arg.Name,
		arg.Label,
		arg.Value,
		arg.ValueType,
		arg.PaymentType,
		arg.ActionMethod,
		arg.IsPublic,
	)
	var i PaymentHistoryAction
	err := row.Scan(
		&i.ID,
		&i.PaymentHistoryID,
		&i.Name,
		&i.Label,
		&i.Value,
		&i.ValueType,
		&i.PaymentType,
		&i.ActionMethod,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePaymentHistoryActionsByPaymentId = `-- name: DeletePaymentHistoryActionsByPaymentId :exec
DELETE FROM payment_history_actions
WHERE payment_history_id = $1
`

func (q *Queries) DeletePaymentHistoryActionsByPaymentId(ctx context.Context, paymentHistoryID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePaymentHistoryActionsByPaymentId, paymentHistoryID)
	return err
}

const getPaymentHistoryActionsByPaymentId = `-- name: GetPaymentHistoryActionsByPaymentId :many
SELECT id, payment_history_id, name, label, value, value_type, payment_type, action_method, is_public, created_at, updated_at FROM payment_history_actions
WHERE payment_history_id = $1
ORDER BY id ASC
`

func (q *Queries) GetPaymentHistoryActionsByPaymentId(ctx context.Context, paymentHistoryID uuid.UUID) ([]PaymentHistoryAction, error) {
	rows, err := q.db.QueryContext(ctx, getPaymentHistoryActionsByPaymentId, paymentHistoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentHistoryAction
	for rows.Next() {
		var i PaymentHistoryAction
		if err := rows.Scan(
			&i.ID,
			&i.PaymentHistoryID,
			&i.Name,
			&i.Label,
			&i.Value,
			&i.ValueType,
			&i.PaymentType,
			&i.ActionMethod,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicPaymentHistoryActionsByPaymentId = `-- name: GetPublicPaymentHistoryActionsByPaymentId :many
SELECT id, payment_history_id, name, label, value, value_type, payment_type, action_method, is_public, created_at, updated_at FROM payment_history_actions
WHERE payment_history_id = $1
AND is_public = TRUE
ORDER BY id ASC
`

func (q *Queries) GetPublicPaymentHistoryActionsByPaymentId(ctx context.Context, paymentHistoryID uuid.UUID) ([]PaymentHistoryAction, error) {
	rows, err := q.db.QueryContext(ctx, getPublicPaymentHistoryActionsByPaymentId, paymentHistoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentHistoryAction
	for rows.Next() {
		var i PaymentHistoryAction
		if err := rows.Scan(
			&i.ID,
			&i.PaymentHistoryID,
			&i.Name,
			&i.Label,
			&i.Value,
			&i.ValueType,
			&i.PaymentType,
			&i.ActionMethod,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
