// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile.sql

package entity

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (name, email, image_url, country_code, phone, description)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, email, image_url, country_code, phone, description, created_at, updated_at
`

type CreateProfileParams struct {
	Name        string         `json:"name"`
	Email       string         `json:"email"`
	ImageUrl    sql.NullString `json:"image_url"`
	CountryCode sql.NullString `json:"country_code"`
	Phone       sql.NullString `json:"phone"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, createProfile,
		arg.Name,
		arg.Email,
		arg.ImageUrl,
		arg.CountryCode,
		arg.Phone,
		arg.Description,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.ImageUrl,
		&i.CountryCode,
		&i.Phone,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByEmail = `-- name: GetProfileByEmail :one
SELECT id, name, email, image_url, country_code, phone, description, created_at, updated_at FROM profiles
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetProfileByEmail(ctx context.Context, email string) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfileByEmail, email)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.ImageUrl,
		&i.CountryCode,
		&i.Phone,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileById = `-- name: GetProfileById :one
SELECT id, name, email, image_url, country_code, phone, description, created_at, updated_at FROM profiles
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProfileById(ctx context.Context, id uuid.UUID) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfileById, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.ImageUrl,
		&i.CountryCode,
		&i.Phone,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
