// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile_referral_code.sql

package entity

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProfileReferralCode = `-- name: CreateProfileReferralCode :one
INSERT INTO profile_referral_codes (profile_id, code, type, is_active, total_discount, discount_type, expired_days, max_discount, max_usage, reward_per_referral)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, profile_id, code, type, is_active, total_discount, discount_type, expired_days, max_discount, max_usage, reward_per_referral, created_at, updated_at, deleted_at
`

type CreateProfileReferralCodeParams struct {
	ProfileID         uuid.UUID     `json:"profile_id"`
	Code              string        `json:"code"`
	Type              ReferralType  `json:"type"`
	IsActive          bool          `json:"is_active"`
	TotalDiscount     int64         `json:"total_discount"`
	DiscountType      DiscountType  `json:"discount_type"`
	ExpiredDays       sql.NullInt32 `json:"expired_days"`
	MaxDiscount       int64         `json:"max_discount"`
	MaxUsage          sql.NullInt32 `json:"max_usage"`
	RewardPerReferral int64         `json:"reward_per_referral"`
}

func (q *Queries) CreateProfileReferralCode(ctx context.Context, arg CreateProfileReferralCodeParams) (ProfileReferralCode, error) {
	row := q.db.QueryRowContext(ctx, createProfileReferralCode,
		arg.ProfileID,
		arg.Code,
		arg.Type,
		arg.IsActive,
		arg.TotalDiscount,
		arg.DiscountType,
		arg.ExpiredDays,
		arg.MaxDiscount,
		arg.MaxUsage,
		arg.RewardPerReferral,
	)
	var i ProfileReferralCode
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Code,
		&i.Type,
		&i.IsActive,
		&i.TotalDiscount,
		&i.DiscountType,
		&i.ExpiredDays,
		&i.MaxDiscount,
		&i.MaxUsage,
		&i.RewardPerReferral,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProfileReferralCodeByCode = `-- name: GetProfileReferralCodeByCode :one
SELECT id, profile_id, code, type, is_active, total_discount, discount_type, expired_days, max_discount, max_usage, reward_per_referral, created_at, updated_at, deleted_at
FROM profile_referral_codes
WHERE code = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetProfileReferralCodeByCode(ctx context.Context, code string) (ProfileReferralCode, error) {
	row := q.db.QueryRowContext(ctx, getProfileReferralCodeByCode, code)
	var i ProfileReferralCode
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Code,
		&i.Type,
		&i.IsActive,
		&i.TotalDiscount,
		&i.DiscountType,
		&i.ExpiredDays,
		&i.MaxDiscount,
		&i.MaxUsage,
		&i.RewardPerReferral,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProfileReferralCodeByProfileIdBasic = `-- name: GetProfileReferralCodeByProfileIdBasic :one
SELECT id, profile_id, code, type, is_active, total_discount, discount_type, expired_days, max_discount, max_usage, reward_per_referral, created_at, updated_at, deleted_at
FROM profile_referral_codes
WHERE profile_id = $1
  AND type = 'basic'
  AND deleted_at IS NULL
`

func (q *Queries) GetProfileReferralCodeByProfileIdBasic(ctx context.Context, profileID uuid.UUID) (ProfileReferralCode, error) {
	row := q.db.QueryRowContext(ctx, getProfileReferralCodeByProfileIdBasic, profileID)
	var i ProfileReferralCode
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Code,
		&i.Type,
		&i.IsActive,
		&i.TotalDiscount,
		&i.DiscountType,
		&i.ExpiredDays,
		&i.MaxDiscount,
		&i.MaxUsage,
		&i.RewardPerReferral,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
