// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package entity

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountBusinessProductsByBusinessRootId(ctx context.Context, arg CountBusinessProductsByBusinessRootIdParams) (int64, error)
	CountJoinedBusinessesByProfileID(ctx context.Context, arg CountJoinedBusinessesByProfileIDParams) (int64, error)
	CreateBusinessKnowledge(ctx context.Context, arg CreateBusinessKnowledgeParams) (BusinessKnowledge, error)
	CreateBusinessMember(ctx context.Context, arg CreateBusinessMemberParams) (BusinessMember, error)
	CreateBusinessProduct(ctx context.Context, arg CreateBusinessProductParams) (BusinessProduct, error)
	CreateBusinessRole(ctx context.Context, arg CreateBusinessRoleParams) (BusinessRole, error)
	CreateBusinessRoot(ctx context.Context) (uuid.UUID, error)
	CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetBusinessKnowledgeByBusinessRootID(ctx context.Context, businessRootID uuid.UUID) (GetBusinessKnowledgeByBusinessRootIDRow, error)
	GetBusinessProductByBusinessProductId(ctx context.Context, id uuid.UUID) (BusinessProduct, error)
	GetBusinessProductsByBusinessRootId(ctx context.Context, arg GetBusinessProductsByBusinessRootIdParams) ([]BusinessProduct, error)
	GetBusinessRoleByBusinessRootID(ctx context.Context, businessRootID uuid.UUID) (BusinessRole, error)
	GetBusinessRootById(ctx context.Context, id uuid.UUID) (GetBusinessRootByIdRow, error)
	GetJoinedBusinessesByProfileID(ctx context.Context, arg GetJoinedBusinessesByProfileIDParams) ([]GetJoinedBusinessesByProfileIDRow, error)
	GetMemberByProfileIdAndBusinessRootId(ctx context.Context, arg GetMemberByProfileIdAndBusinessRootIdParams) (BusinessMember, error)
	GetMembersByBusinessRootID(ctx context.Context, businessRootID uuid.UUID) ([]GetMembersByBusinessRootIDRow, error)
	GetMembersByBusinessRootIDs(ctx context.Context, businessRootIds []uuid.UUID) ([]GetMembersByBusinessRootIDsRow, error)
	GetProfileByEmail(ctx context.Context, email string) (Profile, error)
	GetProfileById(ctx context.Context, id uuid.UUID) (Profile, error)
	GetUserByEmailProfile(ctx context.Context, email string) ([]GetUserByEmailProfileRow, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	ListUsersByProfileId(ctx context.Context, profileID uuid.UUID) ([]User, error)
	SoftDeleteBusinessKnowledgeByBusinessRootID(ctx context.Context, businessRootID uuid.UUID) (uuid.UUID, error)
	SoftDeleteBusinessMemberByBusinessRootID(ctx context.Context, businessRootID uuid.UUID) (uuid.UUID, error)
	SoftDeleteBusinessProductByBusinessProductId(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	SoftDeleteBusinessProductByBusinessRootID(ctx context.Context, businessRootID uuid.UUID) (uuid.UUID, error)
	SoftDeleteBusinessRoleByBusinessRootID(ctx context.Context, businessRootID uuid.UUID) (uuid.UUID, error)
	SoftDeleteBusinessRoot(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	UpdateBusinessProduct(ctx context.Context, arg UpdateBusinessProductParams) (BusinessProduct, error)
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
	UpsertBusinessKnowledgeByBusinessRootID(ctx context.Context, arg UpsertBusinessKnowledgeByBusinessRootIDParams) (BusinessKnowledge, error)
	UpsertBusinessRoleByBusinessRootID(ctx context.Context, arg UpsertBusinessRoleByBusinessRootIDParams) (BusinessRole, error)
	VerifyUser(ctx context.Context, id uuid.UUID) (User, error)
}

var _ Querier = (*Queries)(nil)
