// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: referral_record.sql

package entity

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const checkBusinessUsedReferralCode = `-- name: CheckBusinessUsedReferralCode :one
SELECT EXISTS(
    SELECT 1 FROM referral_records
    WHERE business_root_id = $1 
    AND profile_referral_code_id = $2 
    AND status IN ('pending', 'success')
    AND deleted_at IS NULL
) AS used
`

type CheckBusinessUsedReferralCodeParams struct {
	BusinessRootID        int64 `json:"business_root_id"`
	ProfileReferralCodeID int64 `json:"profile_referral_code_id"`
}

func (q *Queries) CheckBusinessUsedReferralCode(ctx context.Context, arg CheckBusinessUsedReferralCodeParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkBusinessUsedReferralCode, arg.BusinessRootID, arg.ProfileReferralCodeID)
	var used bool
	err := row.Scan(&used)
	return used, err
}

const checkProfileUsedReferralCode = `-- name: CheckProfileUsedReferralCode :one
SELECT EXISTS(
    SELECT 1 FROM referral_records
    WHERE consumer_profile_id = $1 
    AND profile_referral_code_id = $2 
    AND status IN ('pending', 'success')
    AND deleted_at IS NULL
) AS used
`

type CheckProfileUsedReferralCodeParams struct {
	ConsumerProfileID     uuid.UUID `json:"consumer_profile_id"`
	ProfileReferralCodeID int64     `json:"profile_referral_code_id"`
}

func (q *Queries) CheckProfileUsedReferralCode(ctx context.Context, arg CheckProfileUsedReferralCodeParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkProfileUsedReferralCode, arg.ConsumerProfileID, arg.ProfileReferralCodeID)
	var used bool
	err := row.Scan(&used)
	return used, err
}

const countReferralCodeUsage = `-- name: CountReferralCodeUsage :one
SELECT COUNT(*)::int AS count FROM referral_records
WHERE profile_referral_code_id = $1 
AND status IN ('pending', 'success')
AND deleted_at IS NULL
`

func (q *Queries) CountReferralCodeUsage(ctx context.Context, profileReferralCodeID int64) (int32, error) {
	row := q.db.QueryRowContext(ctx, countReferralCodeUsage, profileReferralCodeID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createReferralRecord = `-- name: CreateReferralRecord :one
INSERT INTO referral_records (
    consumer_profile_id,
    business_root_id,
    profile_referral_code_id,
    record_type,
    record_total_discount,
    record_discount_type,
    record_expired_days,
    record_max_discount,
    record_max_usage,
    record_reward_per_referral,
    discount_amount_granted,
    discount_currency,
    reward_amount_granted,
    reward_currency,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
) RETURNING id, consumer_profile_id, business_root_id, profile_referral_code_id, record_type, record_total_discount, record_discount_type, record_expired_days, record_max_discount, record_max_usage, record_reward_per_referral, discount_amount_granted, discount_currency, reward_amount_granted, reward_currency, status, created_at, updated_at, deleted_at
`

type CreateReferralRecordParams struct {
	ConsumerProfileID       uuid.UUID            `json:"consumer_profile_id"`
	BusinessRootID          int64                `json:"business_root_id"`
	ProfileReferralCodeID   int64                `json:"profile_referral_code_id"`
	RecordType              ReferralType         `json:"record_type"`
	RecordTotalDiscount     int64                `json:"record_total_discount"`
	RecordDiscountType      DiscountType         `json:"record_discount_type"`
	RecordExpiredDays       sql.NullInt32        `json:"record_expired_days"`
	RecordMaxDiscount       int64                `json:"record_max_discount"`
	RecordMaxUsage          sql.NullInt32        `json:"record_max_usage"`
	RecordRewardPerReferral int64                `json:"record_reward_per_referral"`
	DiscountAmountGranted   int64                `json:"discount_amount_granted"`
	DiscountCurrency        string               `json:"discount_currency"`
	RewardAmountGranted     int64                `json:"reward_amount_granted"`
	RewardCurrency          string               `json:"reward_currency"`
	Status                  ReferralRecordStatus `json:"status"`
}

func (q *Queries) CreateReferralRecord(ctx context.Context, arg CreateReferralRecordParams) (ReferralRecord, error) {
	row := q.db.QueryRowContext(ctx, createReferralRecord,
		arg.ConsumerProfileID,
		arg.BusinessRootID,
		arg.ProfileReferralCodeID,
		arg.RecordType,
		arg.RecordTotalDiscount,
		arg.RecordDiscountType,
		arg.RecordExpiredDays,
		arg.RecordMaxDiscount,
		arg.RecordMaxUsage,
		arg.RecordRewardPerReferral,
		arg.DiscountAmountGranted,
		arg.DiscountCurrency,
		arg.RewardAmountGranted,
		arg.RewardCurrency,
		arg.Status,
	)
	var i ReferralRecord
	err := row.Scan(
		&i.ID,
		&i.ConsumerProfileID,
		&i.BusinessRootID,
		&i.ProfileReferralCodeID,
		&i.RecordType,
		&i.RecordTotalDiscount,
		&i.RecordDiscountType,
		&i.RecordExpiredDays,
		&i.RecordMaxDiscount,
		&i.RecordMaxUsage,
		&i.RecordRewardPerReferral,
		&i.DiscountAmountGranted,
		&i.DiscountCurrency,
		&i.RewardAmountGranted,
		&i.RewardCurrency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getReferralRecordById = `-- name: GetReferralRecordById :one
SELECT id, consumer_profile_id, business_root_id, profile_referral_code_id, record_type, record_total_discount, record_discount_type, record_expired_days, record_max_discount, record_max_usage, record_reward_per_referral, discount_amount_granted, discount_currency, reward_amount_granted, reward_currency, status, created_at, updated_at, deleted_at FROM referral_records
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetReferralRecordById(ctx context.Context, id int64) (ReferralRecord, error) {
	row := q.db.QueryRowContext(ctx, getReferralRecordById, id)
	var i ReferralRecord
	err := row.Scan(
		&i.ID,
		&i.ConsumerProfileID,
		&i.BusinessRootID,
		&i.ProfileReferralCodeID,
		&i.RecordType,
		&i.RecordTotalDiscount,
		&i.RecordDiscountType,
		&i.RecordExpiredDays,
		&i.RecordMaxDiscount,
		&i.RecordMaxUsage,
		&i.RecordRewardPerReferral,
		&i.DiscountAmountGranted,
		&i.DiscountCurrency,
		&i.RewardAmountGranted,
		&i.RewardCurrency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateReferralRecordStatus = `-- name: UpdateReferralRecordStatus :one
UPDATE referral_records
SET status = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, consumer_profile_id, business_root_id, profile_referral_code_id, record_type, record_total_discount, record_discount_type, record_expired_days, record_max_discount, record_max_usage, record_reward_per_referral, discount_amount_granted, discount_currency, reward_amount_granted, reward_currency, status, created_at, updated_at, deleted_at
`

type UpdateReferralRecordStatusParams struct {
	ID     int64                `json:"id"`
	Status ReferralRecordStatus `json:"status"`
}

func (q *Queries) UpdateReferralRecordStatus(ctx context.Context, arg UpdateReferralRecordStatusParams) (ReferralRecord, error) {
	row := q.db.QueryRowContext(ctx, updateReferralRecordStatus, arg.ID, arg.Status)
	var i ReferralRecord
	err := row.Scan(
		&i.ID,
		&i.ConsumerProfileID,
		&i.BusinessRootID,
		&i.ProfileReferralCodeID,
		&i.RecordType,
		&i.RecordTotalDiscount,
		&i.RecordDiscountType,
		&i.RecordExpiredDays,
		&i.RecordMaxDiscount,
		&i.RecordMaxUsage,
		&i.RecordRewardPerReferral,
		&i.DiscountAmountGranted,
		&i.DiscountCurrency,
		&i.RewardAmountGranted,
		&i.RewardCurrency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
