// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: uploaded_image.sql

package entity

import (
	"context"
)

const getUploadedImageByHashkey = `-- name: GetUploadedImageByHashkey :one
SELECT id, hashkey, public_id, size, image_url, provider, created_at, updated_at FROM uploaded_images WHERE hashkey = $1
`

func (q *Queries) GetUploadedImageByHashkey(ctx context.Context, hashkey string) (UploadedImage, error) {
	row := q.db.QueryRowContext(ctx, getUploadedImageByHashkey, hashkey)
	var i UploadedImage
	err := row.Scan(
		&i.ID,
		&i.Hashkey,
		&i.PublicID,
		&i.Size,
		&i.ImageUrl,
		&i.Provider,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUploadedImage = `-- name: InsertUploadedImage :one
INSERT INTO uploaded_images (hashkey, public_id, image_url, size, provider)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (hashkey)
DO UPDATE SET
  public_id = EXCLUDED.public_id,
  image_url = EXCLUDED.image_url,
  size      = EXCLUDED.size,
  provider  = EXCLUDED.provider
RETURNING id, hashkey, public_id, image_url, size, provider
`

type InsertUploadedImageParams struct {
	Hashkey  string        `json:"hashkey"`
	PublicID string        `json:"public_id"`
	ImageUrl string        `json:"image_url"`
	Size     int64         `json:"size"`
	Provider ImageProvider `json:"provider"`
}

type InsertUploadedImageRow struct {
	ID       int64         `json:"id"`
	Hashkey  string        `json:"hashkey"`
	PublicID string        `json:"public_id"`
	ImageUrl string        `json:"image_url"`
	Size     int64         `json:"size"`
	Provider ImageProvider `json:"provider"`
}

func (q *Queries) InsertUploadedImage(ctx context.Context, arg InsertUploadedImageParams) (InsertUploadedImageRow, error) {
	row := q.db.QueryRowContext(ctx, insertUploadedImage,
		arg.Hashkey,
		arg.PublicID,
		arg.ImageUrl,
		arg.Size,
		arg.Provider,
	)
	var i InsertUploadedImageRow
	err := row.Scan(
		&i.ID,
		&i.Hashkey,
		&i.PublicID,
		&i.ImageUrl,
		&i.Size,
		&i.Provider,
	)
	return i, err
}
