// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package entity

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (profile_id, password, provider)
VALUES ($1, $2, $3)
RETURNING id, password, provider, verified_at, profile_id, created_at, updated_at
`

type CreateUserParams struct {
	ProfileID uuid.UUID      `json:"profile_id"`
	Password  sql.NullString `json:"password"`
	Provider  string         `json:"provider"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.ProfileID, arg.Password, arg.Provider)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Password,
		&i.Provider,
		&i.VerifiedAt,
		&i.ProfileID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailProfile = `-- name: GetUserByEmailProfile :many
SELECT users.id, password, provider, verified_at, profile_id, users.created_at, users.updated_at, profiles.id, name, email, image_url, country_code, phone, description, profiles.created_at, profiles.updated_at FROM users
INNER JOIN profiles ON users.profile_id = profiles.id
WHERE profiles.email = $1
`

type GetUserByEmailProfileRow struct {
	ID          uuid.UUID      `json:"id"`
	Password    sql.NullString `json:"password"`
	Provider    string         `json:"provider"`
	VerifiedAt  sql.NullTime   `json:"verified_at"`
	ProfileID   uuid.UUID      `json:"profile_id"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	ID_2        uuid.UUID      `json:"id_2"`
	Name        string         `json:"name"`
	Email       string         `json:"email"`
	ImageUrl    sql.NullString `json:"image_url"`
	CountryCode sql.NullString `json:"country_code"`
	Phone       sql.NullString `json:"phone"`
	Description sql.NullString `json:"description"`
	CreatedAt_2 sql.NullTime   `json:"created_at_2"`
	UpdatedAt_2 sql.NullTime   `json:"updated_at_2"`
}

func (q *Queries) GetUserByEmailProfile(ctx context.Context, email string) ([]GetUserByEmailProfileRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserByEmailProfile, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserByEmailProfileRow
	for rows.Next() {
		var i GetUserByEmailProfileRow
		if err := rows.Scan(
			&i.ID,
			&i.Password,
			&i.Provider,
			&i.VerifiedAt,
			&i.ProfileID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ID_2,
			&i.Name,
			&i.Email,
			&i.ImageUrl,
			&i.CountryCode,
			&i.Phone,
			&i.Description,
			&i.CreatedAt_2,
			&i.UpdatedAt_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserById = `-- name: GetUserById :one
SELECT id, password, provider, verified_at, profile_id, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Password,
		&i.Provider,
		&i.VerifiedAt,
		&i.ProfileID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsersByProfileId = `-- name: ListUsersByProfileId :many
SELECT id, password, provider, verified_at, profile_id, created_at, updated_at FROM users
WHERE profile_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUsersByProfileId(ctx context.Context, profileID uuid.UUID) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsersByProfileId, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Password,
			&i.Provider,
			&i.VerifiedAt,
			&i.ProfileID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const verifyUser = `-- name: VerifyUser :one
UPDATE users
SET verified_at = now()
WHERE id = $1 RETURNING id, password, provider, verified_at, profile_id, created_at, updated_at
`

func (q *Queries) VerifyUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, verifyUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Password,
		&i.Provider,
		&i.VerifiedAt,
		&i.ProfileID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
